
all_excuses = {
    "general": [
        "Yox e bala, bu iş bizlik deyil.",
        "Mümkün deyil, başqa qapıya.",
        "Heç mənə baxma, alınmaz.",
        "Üzr istəyirəm, amma yox.",
        "Bəlkə gələn əsrdə?",
        "Səndə şans yoxdu, qardaş.",
        "Bu dəfə də alınmadı, bəxtini sonra sınayarsan.",
        "Cavabım qətidir: YOX!",
        "Məşğulam, sonra danışarıq... heç vaxt.",
        "Anam qoymur.",
        "Məclisdəyəm, sonra zəng elə... heç vaxt.",
        "Əvvəl bir insan ol, sonra yenə danışarıq.",
        "Yox, halım yoxdu.",
        "Dedim axı yox!",
        "Gələn dəfə də yox deyəcəm, özünü yorma.",
        "İşim var, başım qarışıqdı.",
        "Başım cəbhə xətti kimidir, yox.",
        "Evdə qonaq var, çıxa bilmərəm.",
        "Bu saatda?",
        "Səninlə hara?",
        "Başqa vaxt, inşallah.",
        "Şərait uyğun deyil, yox.",
        "Əhvalım yoxdu, yox.",
        "Bu gün elə beləyəm, yox.",
        "Nə bilim... yox da.",
        "Heç ağlıma batmadı, yox.",
        "Lazım deyil, yox.",
        "Gözüm görmür, yox.",
        "Eşitmədim nə dedin? Hər halda yox.",
        "Bu saatda yuxum gəlir, yox.",
        "Bu səhər falıma düşmədi, yox.",
        "Ulduzlar düz gəlmədi, yox.",
        "Ayın vəziyyəti icazə vermir, yox.",
        "Dünəndən yorğunam, yox.",
        "Enerjim yoxdu, yox.",
        "Bunu edəsi adam mən deyiləm, yox.",
        "Açıq deyirəm, yox.",
        "Nə isə... yox.",
        "Başqa söhbətdi, yox.",
        "Bu gün yox.",
        "Sabah da yox.",
        "O biri gün də yox.",
        "Ümumiyyətlə yox.",
        "Yoxdur elə şey.",
        "Axtardığın adam mən deyiləm, yox.",
        "Bu mövzu bağlandı, yox.",
        "Faydasızdır, yox.",
        "Vaxt itkisidir, yox.",
        "Sənin üçün darıxdım, amma yox.",
        "Problem səndə deyil, məndədir... və cavab yoxdur.",
        "Kainat icazə vermir, yox.",
        "Təsəvvür elə ki, 'hə' dedim... sonra təsəvvür elə ki, yox dedim.",
        "Şükür Allaha, yox.",
        "Hə? Yox.",
        "Yox, yox, yox. Vəs-salam.",
        "Ağzına su al və yox cavabını qəbul et."
    ],
    "sevgi": [
        "Ürəyim başqasına aiddir, yox.",
        "Sən yaxşı oğlansan/qızsan, amma yox.",
        "Aramızda o qığılcım yoxdu, bağışla.",
        "Dost kimi qalsaq yaxşıdı, ona görə yox.",
        "Hələ tezdir, mənə görə yox.",
        "Qismət deyilmiş, yox.",
        "Xasiyyətimiz tutmur, yox.",
        "Mən sənin bacın kimiyəm, yox.",
        "Bilirəm nə deyəcəksən, amma cavabım yoxdur.",
        "Qəlbim hələ sağalmayıb, yox.",
        "Sevgi mənə görə deyil, yox.",
        "Mən kompleksli adamam, sənə yazığım gəlir, yox.",
        "Evdəkilər qoymaz, yox.",
        "Mənim standartlarım çox yüksəkdir, yox.",
        "Sənə layiq deyiləm, yox.",
        "Bu yaşda sevgi mənlik deyil, yox.",
        "Mən robotam, hissiyyatım yoxdur, yox.",
        "Mən kosmosa köçürəm, yox.",
        "Pişiyim icazə vermir, yox.",
        "Falçı dedi ki, bizdə alınmayacaq, yox.",
        "Əvvəl bir özünə bax, sonra danışarıq, yox.",
        "Sən mənim üçün sadəcə... (söz tapmır)... yoxsan.",
        "Mən azad ruham, bağlanmağı sevmirəm, yox.",
        "Karyeramı qurmalıyam, sevgi sonra, yox.",
        "Elçi göndərin, onda baxarıq... yox.",
        "Bu ssenari tutmaz, yox.",
        "Hisslərim qarışıqdır, yox.",
        "Sən məni başa düşməzsən, yox.",
        "Mən başqa planetdənəm, yox.",
        "Sənin danışığın xoşuma gəlmədi, yox.",
        "Saçının rəngi yox cavabı verir.",
        "Gözlərin... yox deyir.",
        "Yox, yoxdur sevgi zad.",
        "Mən sənə yaraşmıram, yox.",
        "Səninlə olmaqdansa tək ölərəm, yox.",
        "Ürəyimi itirmişəm, tapa bilmirəm, yox.",
        "Mən sevgiyə inamı itirmişəm, yox.",
        "Bu gün qara pişik keçdi qabağımdan, yox.",
        "Gələn həyatda bəlkə... bu həyatda yox.",
        "Mənim taleyimdə sən yoxsan.",
        "Sənə 'hə' desəm, anam hirslənər, yox.",
        "Atam vurar, yox.",
        "Mənim artıq bir balığım var, o mənə bəs edir, yox.",
        "Ürəyimdə boş yer yoxdur, yox.",
        "Sənə qarşı heç nə hiss etmirəm, yox.",
        "Mənə ideal tip lazımdır, o da sən deyilsən, yox.",
        "Çox fikirləşdim... yox.",
        "Yoxsulu oynama, yox.",
        "Bu saatda bu təklif? Yox.",
        "Aramızda uçurum var, yox.",
        "Sən mənim stilim deyilsən, yox.",
        "Bunu sənə kim məsləhət gördü? Yox.",
        "Məni rahat burax, yox.",
        "Get başqasını tap, yox."
    ],
    "dost": [
        "Bu gün planım var, qaqa, yox.",
        "Pul yoxdu, yoxsa gələrdim.",
        "Evdəkilər icazə vermir, yox.",
        "Dərs oxumalıyam, yox.",
        "Yorğunam, heç halım yoxdu.",
        "Sən get, mən çatdıracam özümü (çatdırmadı).",
        "Başım ağrıyır, bu gün yox.",
        "Babat deyiləm, sonra görüşərik.",
        "Başqa vaxt, söz verirəm (vermir).",
        "Bu gün yoldaşımla/sevgilimlə gəzməliyəm, yox.",
        "Qohum gəlib, evdə olmalıyam, yox.",
        "Maşınım yoxdu, necə gəlim? Ona görə yox.",
        "Kefim yoxdu, bağışla, yox.",
        "Nərdə uduzmaq istəmirəm, yox.",
        "Sənə qonaq olmaq istəmirəm, yox.",
        "Bu gün yatmalıyam, yox.",
        "Evə tez gəlməliyəm, yox.",
        "Anam dedi ki, getmə, yox.",
        "Atam dedi ki, otur evdə, yox.",
        "Nənəm xəstələnib, yox.",
        "Dostumun dostu gəlir, mənə yox deyə bilmərəm, sənə yox.",
        "Telefonumun zaryatkası yoxdu, əlaqə saxlaya bilmərik, yox.",
        "Evdə yemək bişirirlər, qaçıra bilmərəm, yox.",
        "Seriala baxmalıyam, yox.",
        "Onlayn oyun oynayırıq, yox.",
        "Bu havada çölə çıxmaq istəmirəm, yox.",
        "Çox istəyərdim, amma yox.",
        "Bu dəfə sən get, mən gələn dəfə gələrəm... bəlkə... yox.",
        "Evdə qapını bağlı qoyub gəlmişəm, qayıtmalıyam, yox.",
        "Açarımı itirmişəm, evə girə bilmirəm, yox.",
        "Bu gün uğursuz gündür, yox.",
        "Yuxumda gördüm ki, getsəm başıma iş gələcək, yox.",
        "Astrolog dedi ki, bu gün evdə qalım, yox.",
        "Pul xərcləmək istəmirəm, yox.",
        "Sənin yanına gəlsəm, mənə nəsə qismət olar, qorxuram, yox.",
        "Özüm tək qalmaq istəyirəm, yox.",
        "Dostlarımı görmək istəmirəm, yox.",
        "Bu görüş mənə fayda verməyəcək, yox.",
        "Vaxtımı səninlə keçirmək istəmirəm, yox.",
        "Sizsiz mənə daha yaxşıdır, yox.",
        "Zəhləm gedir o yerdən, yox.",
        "Sizinlə gəlmək mənə zərərdir, yox.",
        "Bu gün cinlərim təpəmə çıxıb, yox.",
        "Mənə toxunmayın, yox.",
        "Başqa vaxt narahat edin, yox.",
        "Mənim 'yox'um 'hə' deməkdir... amma yox.",
        "Bu gün 'yox' günümdür, yox.",
        "Sənin səsinə yox deyirəm.",
        "Dostluğumuz naminə yox.",
        "Bu görüşə gəlmək mənə ayıbdır, yox.",
        "Gəlməkdən bezmişəm, yox."
    ],
    "muellim": [
        "Tapşırığı etmədim, çünki kosmosda siqnal yox idi.",
        "İnternet kəsilmişdi, ona görə yaza bilmədim, müəllim/ə.",
        "Kitabım evdə qalıb, yoxsa oxuyardım.",
        "Dünən qonağımız var idi, heç cür vaxt olmadı.",
        "Qarnım ağrıyırdı, dərsə fokuslana bilmədim.",
        "Müəllim/ə, vallah başa düşmədim, ona görə yox.",
        "Printer işləmədi, çap edə bilmədim.",
        "Evdə işıqlar sönmüşdü, yoxsa yazardım.",
        "Yuxudan gec durdum, dərsə çatdırana qədər canım çıxdı, tapşırıq qaldı, müəllim/ə.",
        "Dünən başqa dərslərdən tapşırıqlar çox idi, çatdıra bilmədim, müəllim/ə.",
        "Kompyuterim virus tutmuşdu, hər şey silindi, müəllim/ə.",
        "Flashkartımı itirmişəm, tapşırıq onun içində idi, müəllim/ə.",
        "Qeydlərimi səhv dəftərə yazmışam, tapa bilmirəm, müəllim/ə.",
        "Qələmimi itirmişəm, yaza bilmədim, müəllim/ə.",
        "Dəftərimi evdə unutmuşam, müəllim/ə.",
        "Yazmışdım əslində, amma külək apardı, müəllim/ə.",
        "Pişiyim tapşırığı yedi, müəllim/ə.",
        "Balıqlarım dəftərimin üstünə su tökdü, yazılar silindi, müəllim/ə.",
        "Kosmosdan gələn yadplanetlilər tapşırığımı oğurladı, müəllim/ə.",
        "Zaman maşını ilə gələcəyə getdim, tapşırığı sabah edəcəm, müəllim/ə.",
        "Keçmişə getdim, tapşırıq yox idi hələ, müəllim/ə.",
        "Bu gün mənim ad günüm deyil, ona görə etmədim, müəllim/ə.",
        "Atam dedi ki, etmə, müəllim/ə.",
        "Anam dedi ki, mən onsuz da başa düşmürəm bu dərsi, müəllim/ə.",
        "Bacım/qardaşım mənim tapşırığımı öz adından yazıb, müəllim/ə.",
        "Dünən yuxumda gördüm ki, bu tapşırıq ləğv olunub, müəllim/ə.",
        "Mənim yoxluğumda kimsə tapşırığı silib, müəllim/ə.",
        "Əhvalım pis idi, yaza bilmədim, müəllim/ə.",
        "Yazmağa başladım, amma ilham gəlmədi, müəllim/ə.",
        "Tapşırıq çox darıxdırıcı idi, müəllim/ə.",
        "Bu tapşırıq həyatda mənə lazım olmayacaq, müəllim/ə.",
        "Mən tapşırıq etmək üçün yox, öyrənmək üçün gəlmişəm, müəllim/ə.",
        "Dünən dünya dağılırdı, tapşırıq yadından çıxmışdı, müəllim/ə.",
        "Robotlar üsyan etmişdi, tapşırığı onlara verdim, müəllim/ə.",
        "Evdə qaz sızması var idi, tapşırıq yaddan çıxdı, müəllim/ə.",
        "Binamızda yanğın təlimi var idi, müəllim/ə.",
        "Küçədə itim qaçmışdı, onu axtarırdım, müəllim/ə.",
        "Qonşu ilə dava düşdü, tapşırıq yaddan çıxdı, müəllim/ə.",
        "Bu tapşırıq mənim intellektimə uyğun deyil, müəllim/ə.",
        "Tapşırıq çox asan idi, etməyə ehtiyac görmədim, müəllim/ə.",
        "Tapşırıq çox çətin idi, beynim yandı, müəllim/ə.",
        "Səhv tapşırığı etmişəm, müəllim/ə.",
        "Tapşırığın şərtini səhv başa düşmüşəm, müəllim/ə.",
        "Başım o qədər doludur ki, tapşırığa yer qalmadı, müəllim/ə.",
        "Mən tapşırığı beynimdə etdim, yazmağa ehtiyac görmədim, müəllim/ə.",
        "Tapşırıq mənə görə deyil, müəllim/ə.",
        "Bu tapşırıq mənim potensialımı məhdudlaşdırır, müəllim/ə.",
        "Kağız qurtarmışdı, müəllim/ə.",
        "Mürəkkəb qurtarmışdı, müəllim/ə.",
        "Barmaqlarım tutmurdu, müəllim/ə.",
        "Gözlərim görmürdü, müəllim/ə.",
        "Yaddaşım zəifdir, müəllim/ə.",
        "Sinif yoldaşım köçürməyə icazə vermədi, özüm də yazmadım, müəllim/ə.",
        "Bu gün dərsə gəlməyəcəkdim, tapşırıq da etmədim, müəllim/ə.",
        "Sabah edərəm, müəllim/ə.",
        "Gələn dərs edərəm, müəllim/ə."
    ],
    "valideyn": [
        "Dərslərim çoxdur, gedə bilmərəm.",
        "Bu gün yorğunam, heç yerə çıxmaq istəmirəm.",
        "Dostumla dərs çalışacağıq (əslində başqa plan var).",
        "Sabah imtahanım var, olmaz.",
        "Hələ balacayam axı, ora mənlik deyil.",
        "Söz verirəm, gələn dəfə kömək edərəm, bu dəfə yox.",
        "Hamı gedir deyə mən də getməliyəm?",
        "Mənə güvənmirsiz? Yaxşı, getmirəm onda.",
        "Başım ağrıyır, ana/ata.",
        "Özümü yaxşı hiss etmirəm, ana/ata.",
        "Bu paltarla hara gedirəm, ana/ata?",
        "Bu hava mənə düşmür, ana/ata.",
        "Evdə rahatam, heç yerə getmək istəmirəm, ana/ata.",
        "Dostlarım gəlir, ana/ata.",
        "O filan qohumu sevmirəm, ona görə yox, ana/ata.",
        "Orda darıxacam, ana/ata.",
        "Bu saatda evdən çıxmaq olmaz, ana/ata.",
        "Mən böyümüşəm, qərarımı özüm verəcəm: yox, ana/ata.",
        "Mənim öz planlarım var, ana/ata.",
        "Bu iş mənim vəzifə borcum deyil, ana/ata.",
        "Mənə pul versəniz, kömək edərəm, yoxsa yox, ana/ata.",
        "Qonşunun uşağı etmir, mən niyə edim, ana/ata?",
        "Bu iş çox ağırdır, ana/ata.",
        "Əlim batacaq, ana/ata.",
        "Geyimim korlanacaq, ana/ata.",
        "Dırnaqlarım qırılacaq, ana/ata.",
        "Mənə bu barədə deməmişdiniz, ona görə yox, ana/ata.",
        "Unutmuşdum, ana/ata.",
        "Eşitmədim nə dediniz, ana/ata.",
        "Yatmışdım, ana/ata.",
        "Bu gün mənim istirahət günümdür, ana/ata.",
        "Ev işləri mənlik deyil, ana/ata.",
        "Qardaşım/bacım etsin, ana/ata.",
        "Siz özünüz edin, ana/ata.",
        "Vaxtım yoxdur, ana/ata.",
        "Başqa işlərim var, ana/ata.",
        "Zəng edərlər mənə, ana/ata.",
        "Kimsə gəlməlidir bizə, ana/ata.",
        "Pizza sifariş etmişik, gözləyirəm, ana/ata.",
        "Deyəsən xəstələnirəm, ana/ata.",
        "Allergiyam başladı, ana/ata.",
        "Burnum axır, ana/ata.",
        "Öskürürəm, ana/ata.",
        "Başım gicəllənir, ana/ata.",
        "Mənə dərman lazımdır, gedə bilmərəm, ana/ata.",
        "Həkim dedi ki, evdə otur, ana/ata.",
        "Hələ o qədər böyüməmişəm ki, tək gedim, ana/ata.",
        "Mənə icazə verməsəniz, küsərəm, ana/ata.",
        "Siz məni anlamırsınız, ana/ata.",
        "Başqa ailələrdə belə şey yoxdur, ana/ata.",
        "Mən sərbəst olmaq istəyirəm, ana/ata.",
        "Bu tapşırıq mənim gələcək karyerama fayda verməyəcək, ana/ata.",
        "Robot yoxam ki, dediyinizi edim, ana/ata.",
        "Mənə pul verin, köməkçi tutum, ana/ata."
    ],
    "is": [
        "Bu mənim vəzifə borcum deyil, yox.",
        "Hazırda başqa prioritetlərim var, alınmaz.",
        "Bu tapşırıq üçün resurslarım məhduddur, yox.",
        "Komandamızın bu iş üçün vaxtı yoxdur.",
        "Bu ayın büdcəsində nəzərdə tutulmayıb, yox.",
        "Başqa layihə üzərində işləyirəm, buna vaxtım yoxdur.",
        "Bu məsələ ilə bağlı rəhbərliklə danışmaq lazımdır, hələlik yox.",
        "Gələn həftəyə qədər gözləyə bilərsiniz? İndi yox.",
        "Bu iş üçün ekspertiza yoxdur, yox.",
        "Bu tapşırıq strateji hədəflərimizə uyğun deyil, yox.",
        "Risk analizi aparılmayıb, yox.",
        "Hüquqi məhdudiyyətlər var, yox.",
        "Tərəfdaşlarımız razı deyil, yox.",
        "Texniki infrastruktur imkan vermir, yox.",
        "Əlavə işçi qüvvəsi tələb edir, bu yoxdur, yox.",
        "Bu iş üçün motivasiyam yoxdur, yox.",
        "Şirkətin siyasətinə ziddir, yox.",
        "Bu məsələ daxili qaydalarımıza uyğun deyil, yox.",
        "Təhlükəsizlik protokollarına ziddir, yox.",
        "Müştəri məmnuniyyətinə mənfi təsir edə bilər, yox.",
        "Bazarda belə bir tələbat yoxdur, yox.",
        "Rəqiblər bunu etmir, biz niyə edək? Yox.",
        "Bu iş gəlir gətirməyəcək, yox.",
        "Xərclər gözləniləndən çox olacaq, yox.",
        "İnvestisiya cəlbedici deyil, yox.",
        "Layihənin ROI-si aşağıdır, yox.",
        "Qeyri-müəyyənlik çoxdur, yox.",
        "Əlavə təlim tələb edir, vaxt yoxdur, yox.",
        "Komanda daxilində müqavimət var, yox.",
        "Bu işə hazır deyilik, yox.",
        "Bu iş üçün 'buy-in' yoxdur, yox.",
        "Stakeholder-lər razılaşmır, yox.",
        "Bu barədə düşünməyə vaxtım yoxdur, yox.",
        "E-poçtuma baxmamışam, ona görə yox.",
        "Telefonum sönülü idi, yox.",
        "İnternetim kəsildi, yox.",
        "Uzaqdan işləyirəm, mümkün deyil, yox.",
        "Ofisdə deyiləm, yox.",
        "Məzuniyyətdəyəm, yox.",
        "Xəstəyəm, yox.",
        "Şəxsi işlərim var, yox.",
        "Yığıncağım var, yox.",
        "Zəng gözləyirəm, yox.",
        "Başqa bir təcili iş çıxdı, yox.",
        "Yuxum gəlir, yox.",
        "Çay fasiləsindəyəm, yox.",
        "Nahardayam, yox.",
        "İş vaxtı bitdi, yox.",
        "Bu gün Cümədir, yox.",
        "Həftə sonudur, yox.",
        "Bayramdır, yox.",
        "Kompüterim dondu, yox.",
        "Proqram işləmir, yox.",
        "Server çökdü, yox.",
        "Mənim rəhbərimdən icazə almalısınız, yox.",
        "Mən bu barədə səlahiyyətli deyiləm, yox.",
        "Cavabım 'yox'dur, sual verməyin."
    ],

    "toy_yox": [
        "Toyda oynamaq? Yox, dizim dünəndən keyləşib.",
        "Bu musiqinin ritmi mənim qəbilə rəqs stilimə uyğun gəlmir, yox.",
        "Mən qonaq deyiləm, müşahidəçiyəm, yox.",
        "Pulum yoxdur, 'vağzalı' pulu vermək istəmirəm, yox.",
        "Gəlin və bəyə pis göz dəyməsin deyə mən oynamamalıyam, yox."
    ],
    "qonaqliq_yox": [
        "Bu yemək pəhrizimə düşmür, yox.",
        "Dünən o qədər yedim ki, bu həftəlik limitim doldu, yox.",
        "Sizə gəlsəm, qayıtmağa taksi pulum olmaz, ona görə yox.",
        "Evdə itim acdır, onu tək qoya bilmərəm, yox.",
        "Qabları yumağa kömək? Yox, dırnaqlarım təzədir."
    ],
    "yol_yox": [
        "Avtobus gecikdi, ona görə yox.",
        "Yolda qara pişik keçdi, pis əlamətdir, yox.",
        "Benzin yoxdu, yoxsa gələrdim.",
        "Şin partladı... əslində partlamadı, amma yox.",
        "Svetoforda yaşıl işığı gözləyirəm... elə hey gözləyirəm... yox."
    ],
    "sosial_media_yox": [
        "Şəklini like etmək? Yox, barmağım yorğundur.",
        "Paylaşmaq? Yox, səhifəmin 'aura'sını pozar.",
        "Dostluq göndərmək? Yox, artıq 5000 dostum var, limit dolub.",
        "Rəy yazmaq? Yox, sözlərim sığmaz.",
        "Mesaja cavab vermək? Yox, 'görüldü' atmışam da."
    ],
    "oyun_yox": [
        "Oyun oynamaq? Yox, reallıqla əlaqəmi itirmək istəmirəm.",
        "Siz çox güclüsünüz, mənə şans yoxdu, yox.",
        "Valideynlərim kompüterin 'ram'ını bağlayıb, yox.",
        "Bu oyun mənim intellektual səviyyəmə uyğun deyil, yox.",
        "Qəhrəmanımın 'mana'sı qurtarıb, ona görə yox."
    ],
    "texnologiya_yox": [
        "Telefonun zaryatkası yoxdu, yox.",
        "Wi-Fi siqnalı yoxdu, yox.",
        "Proqram yenilənməlidir, vaxtım yoxdu, yox.",
        "Cloud doludur, yaddaşda yer yoxdu, yox.",
        "Sistemdə 'bug' var, işləmir, yox."
    ],
    "pul_yox": [
        "Pul vermək? Yox, 'kraska' almalıyam.",
        "Borc almaq? Yox, qismətə inanıram.",
        "Pulum yoxdu, dünən qumarda uduzdum... zarafat edirəm, yox.",
        "Maaş hələ köçməyib, yox.",
        "Pulum var, amma sənə vermərəm, yox."
    ],
    "saglamliq_yox": [
        "Pəhriz saxlamaq? Yox, yaşamağın nə mənası qalar?",
        "İdman etmək? Yox, bədənim tənbəlliyə öyrəşib.",
        "Erkən yatmaq? Yox, gecələr daha kreativ oluram.",
        "Həkimə getmək? Yox, özüm öz həkimiməm.",
        "Özümü yaxşı hiss etmirəm... yox, sadəcə etmək istəmirəm."
    ],
    "qonsu_yox": [
        "Duz vermək? Yox, duzum qurtarıb.",
        "Alət vermək? Yox, o alət sirli ayinlər üçün istifadə olunur, verə bilmərəm.",
        "Uşağa baxmaq? Yox, uşaqlar kosmosdan gələn siqnallara həssasdırlar, mən də onlara, risk etmək istəmirəm.",
        "Məktub qəbul etmək? Yox, başqa qonşu qəbul etsin.",
        "Səs kəsmək? Yox, mən yaradıcılıq prosesindəyəm, bu səslər ilham mənbəyidir."
    ],
    "burokratiya_yox": [
        "Sənəd düzəltmək? Yox, sistem işləmir.",
        "Növbə gözləmək? Yox, mənim vaxtım qiymətlidir.",
        "Ərizə yazmaq? Yox, qələmim yoxdur.",
        "Gələn həftə gəlin? Yox, gələn həftə planetlərin düzülüşü mənə düşmür.",
        "Problem həll olundu? Yox, 'server'də xəta var."
    ],
    "ev_isleri_yox": [
        "Paltar yumaq? Yox, su qənaət etməliyik.",
        "Toz almaq? Yox, tozlar da kainatın bir hissəsidir, onlarla birlikdə yaşamağa öyrəşməliyik.",
        "Qab yumaq? Yox, qablar öz-özünə təmizlənən nanobotlarla örtülüb... hələ yox.",
        "Zibil atmaq? Yox, bu gün zibil maşınları tətil elan edib.",
        "Otağı yığışdırmaq? Yox, bu 'xaos' mənim 'kreativ'liyim üçün vacibdir."
    ],
    "felsefi_yox": [
        "Etmək? Yox, var olmaq üçün etmək vacib deyil.",
        "Nə üçün? Yox.",
        "Həyatın mənası... tapşırığı etməməyimdədir, yox.",
        "Mən kainatın 'yox' cavabının təcəssümüyəm, yox.",
        "Hər 'hə' bir 'yox'dur, ona görə sadəcə 'yox' deyirəm."
    ],
     "hava_yox": [
        "Bu havada çölə çıxmaq? Yox, canıma qənim deyiləm.",
        "Yağış yağır, yox.",
        "Çox istidir/soyuğdur, yox.",
        "Küləkdir, saçım dağılacaq, yox.",
        "Havanın rütubəti mənə düşmür, yox."
     ],
    "paltar_yox": [
        "Geyinmək? Yox, geyinməyə heç nəyim yoxdur.",
        "Bu paltarla hara gedirəm? Yox.",
        "Paltarım təmiz deyil, yox.",
        "Ütülənməyib, yox.",
        "Moddan düşüb, yox."
    ]
}