
all_excuses = {
    "general": [
        "Yox e bala, bu iş bizlik deyil.",
        "Mümkün deyil, başqa qapıya.",
        "Heç mənə baxma, alınmaz.",
        "Üzr istəyirəm, amma yox.",
        "Bəlkə gələn əsrdə?",
        "Səndə şans yoxdu, qardaş.",
        "Bu dəfə də alınmadı, bəxtini sonra sınayarsan.",
        "Cavabım qətidir: YOX!",
        "Məşğulam, sonra danışarıq... heç vaxt.",
        "Anam qoymur.",
        "Məclisdəyəm, sonra zəng elə... heç vaxt.",
        "Əvvəl bir insan ol, sonra yenə danışarıq.",
        "Yox, halım yoxdu.",
        "Dedim axı yox!",
        "Gələn dəfə də yox deyəcəm, özünü yorma.",
        "İşim var, başım qarışıqdı.",
        "Başım cəbhə xətti kimidir, yox.",
        "Evdə qonaq var, çıxa bilmərəm.",
        "Bu saatda?",
        "Səninlə hara?",
        "Başqa vaxt, inşallah.",
        "Şərait uyğun deyil, yox.",
        "Əhvalım yoxdu, yox.",
        "Bu gün elə beləyəm, yox.",
        "Nə bilim... yox da.",
        "Heç ağlıma batmadı, yox.",
        "Lazım deyil, yox.",
        "Gözüm görmür, yox.",
        "Eşitmədim nə dedin? Hər halda yox.",
        "Bu saatda yuxum gəlir, yox.",
        "Bu səhər falıma düşmədi, yox.",
        "Ulduzlar düz gəlmədi, yox.",
        "Ayın vəziyyəti icazə vermir, yox.",
        "Dünəndən yorğunam, yox.",
        "Enerjim yoxdu, yox.",
        "Bunu edəsi adam mən deyiləm, yox.",
        "Açıq deyirəm, yox.",
        "Nə isə... yox.",
        "Başqa söhbətdi, yox.",
        "Bu gün yox.",
        "Sabah da yox.",
        "O biri gün də yox.",
        "Ümumiyyətlə yox.",
        "Yoxdur elə şey.",
        "Axtardığın adam mən deyiləm, yox.",
        "Bu mövzu bağlandı, yox.",
        "Faydasızdır, yox.",
        "Vaxt itkisidir, yox.",
        "Sənin üçün darıxdım, amma yox.",
        "Problem səndə deyil, məndədir... və cavab yoxdur.",
        "Kainat icazə vermir, yox.",
        "Təsəvvür elə ki, 'hə' dedim... sonra təsəvvür elə ki, yox dedim.",
        "Şükür Allaha, yox.",
        "Hə? Yox.",
        "Yox, yox, yox. Vəs-salam.",
        "Ağzına su al və yox cavabını qəbul et."
    ],
    "sevgi": [
        "Ürəyim başqasına aiddir, yox.",
        "Sən yaxşı oğlansan/qızsan, amma yox.",
        "Aramızda o qığılcım yoxdu, bağışla.",
        "Dost kimi qalsaq yaxşıdı, ona görə yox.",
        "Hələ tezdir, mənə görə yox.",
        "Qismət deyilmiş, yox.",
        "Xasiyyətimiz tutmur, yox.",
        "Mən sənin bacın kimiyəm, yox.",
        "Bilirəm nə deyəcəksən, amma cavabım yoxdur.",
        "Qəlbim hələ sağalmayıb, yox.",
        "Sevgi mənə görə deyil, yox.",
        "Mən kompleksli adamam, sənə yazığım gəlir, yox.",
        "Evdəkilər qoymaz, yox.",
        "Mənim standartlarım çox yüksəkdir, yox.",
        "Sənə layiq deyiləm, yox.",
        "Bu yaşda sevgi mənlik deyil, yox.",
        "Mən robotam, hissiyyatım yoxdur, yox.",
        "Mən kosmosa köçürəm, yox.",
        "Pişiyim icazə vermir, yox.",
        "Falçı dedi ki, bizdə alınmayacaq, yox.",
        "Əvvəl bir özünə bax, sonra danışarıq, yox.",
        "Sən mənim üçün sadəcə... (söz tapmır)... yoxsan.",
        "Mən azad ruham, bağlanmağı sevmirəm, yox.",
        "Karyeramı qurmalıyam, sevgi sonra, yox.",
        "Elçi göndərin, onda baxarıq... yox.",
        "Bu ssenari tutmaz, yox.",
        "Hisslərim qarışıqdır, yox.",
        "Sən məni başa düşməzsən, yox.",
        "Mən başqa planetdənəm, yox.",
        "Sənin danışığın xoşuma gəlmədi, yox.",
        "Saçının rəngi yox cavabı verir.",
        "Gözlərin... yox deyir.",
        "Yox, yoxdur sevgi zad.",
        "Mən sənə yaraşmıram, yox.",
        "Səninlə olmaqdansa tək ölərəm, yox.",
        "Ürəyimi itirmişəm, tapa bilmirəm, yox.",
        "Mən sevgiyə inamı itirmişəm, yox.",
        "Bu gün qara pişik keçdi qabağımdan, yox.",
        "Gələn həyatda bəlkə... bu həyatda yox.",
        "Mənim taleyimdə sən yoxsan.",
        "Sənə 'hə' desəm, anam hirslənər, yox.",
        "Atam vurar, yox.",
        "Mənim artıq bir balığım var, o mənə bəs edir, yox.",
        "Ürəyimdə boş yer yoxdur, yox.",
        "Sənə qarşı heç nə hiss etmirəm, yox.",
        "Mənə ideal tip lazımdır, o da sən deyilsən, yox.",
        "Çox fikirləşdim... yox.",
        "Yoxsulu oynama, yox.",
        "Bu saatda bu təklif? Yox.",
        "Aramızda uçurum var, yox.",
        "Sən mənim stilim deyilsən, yox.",
        "Bunu sənə kim məsləhət gördü? Yox.",
        "Məni rahat burax, yox.",
        "Get başqasını tap, yox."
    ],
    "dost": [
        "Bu gün planım var, qaqa, yox.",
        "Pul yoxdu, yoxsa gələrdim.",
        "Evdəkilər icazə vermir, yox.",
        "Dərs oxumalıyam, yox.",
        "Yorğunam, heç halım yoxdu.",
        "Sən get, mən çatdıracam özümü (çatdırmadı).",
        "Başım ağrıyır, bu gün yox.",
        "Babat deyiləm, sonra görüşərik.",
        "Başqa vaxt, söz verirəm (vermir).",
        "Bu gün yoldaşımla/sevgilimlə gəzməliyəm, yox.",
        "Qohum gəlib, evdə olmalıyam, yox.",
        "Maşınım yoxdu, necə gəlim? Ona görə yox.",
        "Kefim yoxdu, bağışla, yox.",
        "Nərdə uduzmaq istəmirəm, yox.",
        "Sənə qonaq olmaq istəmirəm, yox.",
        "Bu gün yatmalıyam, yox.",
        "Evə tez gəlməliyəm, yox.",
        "Anam dedi ki, getmə, yox.",
        "Atam dedi ki, otur evdə, yox.",
        "Nənəm xəstələnib, yox.",
        "Dostumun dostu gəlir, mənə yox deyə bilmərəm, sənə yox.",
        "Telefonumun zaryatkası yoxdu, əlaqə saxlaya bilmərik, yox.",
        "Evdə yemək bişirirlər, qaçıra bilmərəm, yox.",
        "Seriala baxmalıyam, yox.",
        "Onlayn oyun oynayırıq, yox.",
        "Bu havada çölə çıxmaq istəmirəm, yox.",
        "Çox istəyərdim, amma yox.",
        "Bu dəfə sən get, mən gələn dəfə gələrəm... bəlkə... yox.",
        "Evdə qapını bağlı qoyub gəlmişəm, qayıtmalıyam, yox.",
        "Açarımı itirmişəm, evə girə bilmirəm, yox.",
        "Bu gün uğursuz gündür, yox.",
        "Yuxumda gördüm ki, getsəm başıma iş gələcək, yox.",
        "Astrolog dedi ki, bu gün evdə qalım, yox.",
        "Pul xərcləmək istəmirəm, yox.",
        "Sənin yanına gəlsəm, mənə nəsə qismət olar, qorxuram, yox.",
        "Özüm tək qalmaq istəyirəm, yox.",
        "Dostlarımı görmək istəmirəm, yox.",
        "Bu görüş mənə fayda verməyəcək, yox.",
        "Vaxtımı səninlə keçirmək istəmirəm, yox.",
        "Sizsiz mənə daha yaxşıdır, yox.",
        "Zəhləm gedir o yerdən, yox.",
        "Sizinlə gəlmək mənə zərərdir, yox.",
        "Bu gün cinlərim təpəmə çıxıb, yox.",
        "Mənə toxunmayın, yox.",
        "Başqa vaxt narahat edin, yox.",
        "Mənim 'yox'um 'hə' deməkdir... amma yox.",
        "Bu gün 'yox' günümdür, yox.",
        "Sənin səsinə yox deyirəm.",
        "Dostluğumuz naminə yox.",
        "Bu görüşə gəlmək mənə ayıbdır, yox.",
        "Gəlməkdən bezmişəm, yox."
    ],
    "muellim": [
        "Tapşırığı etmədim, çünki kosmosda siqnal yox idi.",
        "İnternet kəsilmişdi, ona görə yaza bilmədim, müəllim/ə.",
        "Kitabım evdə qalıb, yoxsa oxuyardım.",
        "Dünən qonağımız var idi, heç cür vaxt olmadı.",
        "Qarnım ağrıyırdı, dərsə fokuslana bilmədim.",
        "Müəllim/ə, vallah başa düşmədim, ona görə yox.",
        "Printer işləmədi, çap edə bilmədim.",
        "Evdə işıqlar sönmüşdü, yoxsa yazardım.",
        "Yuxudan gec durdum, dərsə çatdırana qədər canım çıxdı, tapşırıq qaldı, müəllim/ə.",
        "Dünən başqa dərslərdən tapşırıqlar çox idi, çatdıra bilmədim, müəllim/ə.",
        "Kompyuterim virus tutmuşdu, hər şey silindi, müəllim/ə.",
        "Flashkartımı itirmişəm, tapşırıq onun içində idi, müəllim/ə.",
        "Qeydlərimi səhv dəftərə yazmışam, tapa bilmirəm, müəllim/ə.",
        "Qələmimi itirmişəm, yaza bilmədim, müəllim/ə.",
        "Dəftərimi evdə unutmuşam, müəllim/ə.",
        "Yazmışdım əslində, amma külək apardı, müəllim/ə.",
        "Pişiyim tapşırığı yedi, müəllim/ə.",
        "Balıqlarım dəftərimin üstünə su tökdü, yazılar silindi, müəllim/ə.",
        "Kosmosdan gələn yadplanetlilər tapşırığımı oğurladı, müəllim/ə.",
        "Zaman maşını ilə gələcəyə getdim, tapşırığı sabah edəcəm, müəllim/ə.",
        "Keçmişə getdim, tapşırıq yox idi hələ, müəllim/ə.",
        "Bu gün mənim ad günüm deyil, ona görə etmədim, müəllim/ə.",
        "Atam dedi ki, etmə, müəllim/ə.",
        "Anam dedi ki, mən onsuz da başa düşmürəm bu dərsi, müəllim/ə.",
        "Bacım/qardaşım mənim tapşırığımı öz adından yazıb, müəllim/ə.",
        "Dünən yuxumda gördüm ki, bu tapşırıq ləğv olunub, müəllim/ə.",
        "Mənim yoxluğumda kimsə tapşırığı silib, müəllim/ə.",
        "Əhvalım pis idi, yaza bilmədim, müəllim/ə.",
        "Yazmağa başladım, amma ilham gəlmədi, müəllim/ə.",
        "Tapşırıq çox darıxdırıcı idi, müəllim/ə.",
        "Bu tapşırıq həyatda mənə lazım olmayacaq, müəllim/ə.",
        "Mən tapşırıq etmək üçün yox, öyrənmək üçün gəlmişəm, müəllim/ə.",
        "Dünən dünya dağılırdı, tapşırıq yadından çıxmışdı, müəllim/ə.",
        "Robotlar üsyan etmişdi, tapşırığı onlara verdim, müəllim/ə.",
        "Evdə qaz sızması var idi, tapşırıq yaddan çıxdı, müəllim/ə.",
        "Binamızda yanğın təlimi var idi, müəllim/ə.",
        "Küçədə itim qaçmışdı, onu axtarırdım, müəllim/ə.",
        "Qonşu ilə dava düşdü, tapşırıq yaddan çıxdı, müəllim/ə.",
        "Bu tapşırıq mənim intellektimə uyğun deyil, müəllim/ə.",
        "Tapşırıq çox asan idi, etməyə ehtiyac görmədim, müəllim/ə.",
        "Tapşırıq çox çətin idi, beynim yandı, müəllim/ə.",
        "Səhv tapşırığı etmişəm, müəllim/ə.",
        "Tapşırığın şərtini səhv başa düşmüşəm, müəllim/ə.",
        "Başım o qədər doludur ki, tapşırığa yer qalmadı, müəllim/ə.",
        "Mən tapşırığı beynimdə etdim, yazmağa ehtiyac görmədim, müəllim/ə.",
        "Tapşırıq mənə görə deyil, müəllim/ə.",
        "Bu tapşırıq mənim potensialımı məhdudlaşdırır, müəllim/ə.",
        "Kağız qurtarmışdı, müəllim/ə.",
        "Mürəkkəb qurtarmışdı, müəllim/ə.",
        "Barmaqlarım tutmurdu, müəllim/ə.",
        "Gözlərim görmürdü, müəllim/ə.",
        "Yaddaşım zəifdir, müəllim/ə.",
        "Sinif yoldaşım köçürməyə icazə vermədi, özüm də yazmadım, müəllim/ə.",
        "Bu gün dərsə gəlməyəcəkdim, tapşırıq da etmədim, müəllim/ə.",
        "Sabah edərəm, müəllim/ə.",
        "Gələn dərs edərəm, müəllim/ə."
    ],
    "valideyn": [
        "Dərslərim çoxdur, gedə bilmərəm.",
        "Bu gün yorğunam, heç yerə çıxmaq istəmirəm.",
        "Dostumla dərs çalışacağıq (əslində başqa plan var).",
        "Sabah imtahanım var, olmaz.",
        "Hələ balacayam axı, ora mənlik deyil.",
        "Söz verirəm, gələn dəfə kömək edərəm, bu dəfə yox.",
        "Hamı gedir deyə mən də getməliyəm?",
        "Mənə güvənmirsiz? Yaxşı, getmirəm onda.",
        "Başım ağrıyır, ana/ata.",
        "Özümü yaxşı hiss etmirəm, ana/ata.",
        "Bu paltarla hara gedirəm, ana/ata?",
        "Bu hava mənə düşmür, ana/ata.",
        "Evdə rahatam, heç yerə getmək istəmirəm, ana/ata.",
        "Dostlarım gəlir, ana/ata.",
        "O filan qohumu sevmirəm, ona görə yox, ana/ata.",
        "Orda darıxacam, ana/ata.",
        "Bu saatda evdən çıxmaq olmaz, ana/ata.",
        "Mən böyümüşəm, qərarımı özüm verəcəm: yox, ana/ata.",
        "Mənim öz planlarım var, ana/ata.",
        "Bu iş mənim vəzifə borcum deyil, ana/ata.",
        "Mənə pul versəniz, kömək edərəm, yoxsa yox, ana/ata.",
        "Qonşunun uşağı etmir, mən niyə edim, ana/ata?",
        "Bu iş çox ağırdır, ana/ata.",
        "Əlim batacaq, ana/ata.",
        "Geyimim korlanacaq, ana/ata.",
        "Dırnaqlarım qırılacaq, ana/ata.",
        "Mənə bu barədə deməmişdiniz, ona görə yox, ana/ata.",
        "Unutmuşdum, ana/ata.",
        "Eşitmədim nə dediniz, ana/ata.",
        "Yatmışdım, ana/ata.",
        "Bu gün mənim istirahət günümdür, ana/ata.",
        "Ev işləri mənlik deyil, ana/ata.",
        "Qardaşım/bacım etsin, ana/ata.",
        "Siz özünüz edin, ana/ata.",
        "Vaxtım yoxdur, ana/ata.",
        "Başqa işlərim var, ana/ata.",
        "Zəng edərlər mənə, ana/ata.",
        "Kimsə gəlməlidir bizə, ana/ata.",
        "Pizza sifariş etmişik, gözləyirəm, ana/ata.",
        "Deyəsən xəstələnirəm, ana/ata.",
        "Allergiyam başladı, ana/ata.",
        "Burnum axır, ana/ata.",
        "Öskürürəm, ana/ata.",
        "Başım gicəllənir, ana/ata.",
        "Mənə dərman lazımdır, gedə bilmərəm, ana/ata.",
        "Həkim dedi ki, evdə otur, ana/ata.",
        "Hələ o qədər böyüməmişəm ki, tək gedim, ana/ata.",
        "Mənə icazə verməsəniz, küsərəm, ana/ata.",
        "Siz məni anlamırsınız, ana/ata.",
        "Başqa ailələrdə belə şey yoxdur, ana/ata.",
        "Mən sərbəst olmaq istəyirəm, ana/ata.",
        "Bu tapşırıq mənim gələcək karyerama fayda verməyəcək, ana/ata.",
        "Robot yoxam ki, dediyinizi edim, ana/ata.",
        "Mənə pul verin, köməkçi tutum, ana/ata."
    ],
    "is": [
        "Bu mənim vəzifə borcum deyil, yox.",
        "Hazırda başqa prioritetlərim var, alınmaz.",
        "Bu tapşırıq üçün resurslarım məhduddur, yox.",
        "Komandamızın bu iş üçün vaxtı yoxdur.",
        "Bu ayın büdcəsində nəzərdə tutulmayıb, yox.",
        "Başqa layihə üzərində işləyirəm, buna vaxtım yoxdur.",
        "Bu məsələ ilə bağlı rəhbərliklə danışmaq lazımdır, hələlik yox.",
        "Gələn həftəyə qədər gözləyə bilərsiniz? İndi yox.",
        "Bu iş üçün ekspertiza yoxdur, yox.",
        "Bu tapşırıq strateji hədəflərimizə uyğun deyil, yox.",
        "Risk analizi aparılmayıb, yox.",
        "Hüquqi məhdudiyyətlər var, yox.",
        "Tərəfdaşlarımız razı deyil, yox.",
        "Texniki infrastruktur imkan vermir, yox.",
        "Əlavə işçi qüvvəsi tələb edir, bu yoxdur, yox.",
        "Bu iş üçün motivasiyam yoxdur, yox.",
        "Şirkətin siyasətinə ziddir, yox.",
        "Bu məsələ daxili qaydalarımıza uyğun deyil, yox.",
        "Təhlükəsizlik protokollarına ziddir, yox.",
        "Müştəri məmnuniyyətinə mənfi təsir edə bilər, yox.",
        "Bazarda belə bir tələbat yoxdur, yox.",
        "Rəqiblər bunu etmir, biz niyə edək? Yox.",
        "Bu iş gəlir gətirməyəcək, yox.",
        "Xərclər gözləniləndən çox olacaq, yox.",
        "İnvestisiya cəlbedici deyil, yox.",
        "Layihənin ROI-si aşağıdır, yox.",
        "Qeyri-müəyyənlik çoxdur, yox.",
        "Əlavə təlim tələb edir, vaxt yoxdur, yox.",
        "Komanda daxilində müqavimət var, yox.",
        "Bu işə hazır deyilik, yox.",
        "Bu iş üçün 'buy-in' yoxdur, yox.",
        "Stakeholder-lər razılaşmır, yox.",
        "Bu barədə düşünməyə vaxtım yoxdur, yox.",
        "E-poçtuma baxmamışam, ona görə yox.",
        "Telefonum sönülü idi, yox.",
        "İnternetim kəsildi, yox.",
        "Uzaqdan işləyirəm, mümkün deyil, yox.",
        "Ofisdə deyiləm, yox.",
        "Məzuniyyətdəyəm, yox.",
        "Xəstəyəm, yox.",
        "Şəxsi işlərim var, yox.",
        "Yığıncağım var, yox.",
        "Zəng gözləyirəm, yox.",
        "Başqa bir təcili iş çıxdı, yox.",
        "Yuxum gəlir, yox.",
        "Çay fasiləsindəyəm, yox.",
        "Nahardayam, yox.",
        "İş vaxtı bitdi, yox.",
        "Bu gün Cümədir, yox.",
        "Həftə sonudur, yox.",
        "Bayramdır, yox.",
        "Kompüterim dondu, yox.",
        "Proqram işləmir, yox.",
        "Server çökdü, yox.",
        "Mənim rəhbərimdən icazə almalısınız, yox.",
        "Mən bu barədə səlahiyyətli deyiləm, yox.",
        "Cavabım 'yox'dur, sual verməyin."
    ],

    "toy_yox": [
        "Toyda oynamaq? Yox, dizim dünəndən keyləşib.",
        "Bu musiqinin ritmi mənim qəbilə rəqs stilimə uyğun gəlmir, yox.",
        "Mən qonaq deyiləm, müşahidəçiyəm, yox.",
        "Pulum yoxdur, 'vağzalı' pulu vermək istəmirəm, yox.",
        "Gəlin və bəyə pis göz dəyməsin deyə mən oynamamalıyam, yox."
    ],
    "qonaqliq_yox": [
        "Bu yemək pəhrizimə düşmür, yox.",
        "Dünən o qədər yedim ki, bu həftəlik limitim doldu, yox.",
        "Sizə gəlsəm, qayıtmağa taksi pulum olmaz, ona görə yox.",
        "Evdə itim acdır, onu tək qoya bilmərəm, yox.",
        "Qabları yumağa kömək? Yox, dırnaqlarım təzədir."
    ],
    "yol_yox": [
        "Avtobus gecikdi, ona görə yox.",
        "Yolda qara pişik keçdi, pis əlamətdir, yox.",
        "Benzin yoxdu, yoxsa gələrdim.",
        "Şin partladı... əslində partlamadı, amma yox.",
        "Svetoforda yaşıl işığı gözləyirəm... elə hey gözləyirəm... yox."
    ],
    "sosial_media_yox": [
        "Şəklini like etmək? Yox, barmağım yorğundur.",
        "Paylaşmaq? Yox, səhifəmin 'aura'sını pozar.",
        "Dostluq göndərmək? Yox, artıq 5000 dostum var, limit dolub.",
        "Rəy yazmaq? Yox, sözlərim sığmaz.",
        "Mesaja cavab vermək? Yox, 'görüldü' atmışam da."
    ],
    "oyun_yox": [
        "Oyun oynamaq? Yox, reallıqla əlaqəmi itirmək istəmirəm.",
        "Siz çox güclüsünüz, mənə şans yoxdu, yox.",
        "Valideynlərim kompüterin 'ram'ını bağlayıb, yox.",
        "Bu oyun mənim intellektual səviyyəmə uyğun deyil, yox.",
        "Qəhrəmanımın 'mana'sı qurtarıb, ona görə yox."
    ],
    "texnologiya_yox": [
        "Telefonun zaryatkası yoxdu, yox.",
        "Wi-Fi siqnalı yoxdu, yox.",
        "Proqram yenilənməlidir, vaxtım yoxdu, yox.",
        "Cloud doludur, yaddaşda yer yoxdu, yox.",
        "Sistemdə 'bug' var, işləmir, yox."
    ],
    "pul_yox": [
        "Pul vermək? Yox, 'kraska' almalıyam.",
        "Borc almaq? Yox, qismətə inanıram.",
        "Pulum yoxdu, dünən qumarda uduzdum... zarafat edirəm, yox.",
        "Maaş hələ köçməyib, yox.",
        "Pulum var, amma sənə vermərəm, yox."
    ],
    "saglamliq_yox": [
        "Pəhriz saxlamaq? Yox, yaşamağın nə mənası qalar?",
        "İdman etmək? Yox, bədənim tənbəlliyə öyrəşib.",
        "Erkən yatmaq? Yox, gecələr daha kreativ oluram.",
        "Həkimə getmək? Yox, özüm öz həkimiməm.",
        "Özümü yaxşı hiss etmirəm... yox, sadəcə etmək istəmirəm."
    ],
    "qonsu_yox": [
        "Duz vermək? Yox, duzum qurtarıb.",
        "Alət vermək? Yox, o alət sirli ayinlər üçün istifadə olunur, verə bilmərəm.",
        "Uşağa baxmaq? Yox, uşaqlar kosmosdan gələn siqnallara həssasdırlar, mən də onlara, risk etmək istəmirəm.",
        "Məktub qəbul etmək? Yox, başqa qonşu qəbul etsin.",
        "Səs kəsmək? Yox, mən yaradıcılıq prosesindəyəm, bu səslər ilham mənbəyidir."
    ],
    "burokratiya_yox": [
        "Sənəd düzəltmək? Yox, sistem işləmir.",
        "Növbə gözləmək? Yox, mənim vaxtım qiymətlidir.",
        "Ərizə yazmaq? Yox, qələmim yoxdur.",
        "Gələn həftə gəlin? Yox, gələn həftə planetlərin düzülüşü mənə düşmür.",
        "Problem həll olundu? Yox, 'server'də xəta var."
    ],
    "ev_isleri_yox": [
        "Paltar yumaq? Yox, su qənaət etməliyik.",
        "Toz almaq? Yox, tozlar da kainatın bir hissəsidir, onlarla birlikdə yaşamağa öyrəşməliyik.",
        "Qab yumaq? Yox, qablar öz-özünə təmizlənən nanobotlarla örtülüb... hələ yox.",
        "Zibil atmaq? Yox, bu gün zibil maşınları tətil elan edib.",
        "Otağı yığışdırmaq? Yox, bu 'xaos' mənim 'kreativ'liyim üçün vacibdir."
    ],
    "felsefi_yox": [
        "Etmək? Yox, var olmaq üçün etmək vacib deyil.",
        "Nə üçün? Yox.",
        "Həyatın mənası... tapşırığı etməməyimdədir, yox.",
        "Mən kainatın 'yox' cavabının təcəssümüyəm, yox.",
        "Hər 'hə' bir 'yox'dur, ona görə sadəcə 'yox' deyirəm."
    ],
     "hava_yox": [
        "Bu havada çölə çıxmaq? Yox, canıma qənim deyiləm.",
        "Yağış yağır, yox.",
        "Çox istidir/soyuğdur, yox.",
        "Küləkdir, saçım dağılacaq, yox.",
        "Havanın rütubəti mənə düşmür, yox."
     ],
    "paltar_yox": [
        "Geyinmək? Yox, geyinməyə heç nəyim yoxdur.",
        "Bu paltarla hara gedirəm? Yox.",
        "Paltarım təmiz deyil, yox.",
        "Ütülənməyib, yox.",
        "Moddan düşüb, yox."
    ],
    {
  "general_yeni": [
    "Bu gün kainat mənimlə eyni fikirdə deyil, ona görə yox.",
    "Mənim daxili uşağım buna 'yox' deyir, onu incidə bilmərəm.",
    "Enerji səviyyəm ancaq nəfəs almağa çatır, əlavə heç nəyə yox.",
    "Bu məsələ mənim 'bu həftəlik problem kvotamı' aşır.",
    "Mən bu iş üçün çox bahalıyam... yəni, mənəvi olaraq.",
    "Xarakterim buna icazə vermir, çox prinsipialam.",
    "Bu gün 'özümə qulluq' günümdür, bura 'yox' demək də daxildir.",
    "Mənim şəxsi astroloqum bu gün üçün mənfi proqnoz verib.",
    "Sizə 'hə' desəm, paralel kainatda bir problem yaranar.",
    "Bu iş mənim auramı korlaya bilər, riskə gedə bilmərəm.",
    "Hal-hazırda yalnız şokoladla bağlı təkliflərə açığam.",
    "Mənim üçün çox mürəkkəbdir, beynim hələ beta versiyadadır.",
    "Bu günkü planlarımda 'spontan qərarlar' bəndi yox idi.",
    "Vicdanım sızlayır, amma 'yox' deməliyəm.",
    "Bu, mənim komfort zonamdan bir neçə parsek uzaqdadır.",
    "Mən bu aralar ancaq 'offline' rejimdə mövcudam.",
    "Ruh halım buna uyğun deyil, bəlkə başqa bir reinkarnasiyada.",
    "Bu təklif mənim daxili harmoniyamı pozur.",
    "Mən bu gün 'minimalizm' fəlsəfəsini yaşayıram, yəni minimal hərəkət.",
    "Beynimdəki 'error 404: motivasiya tapılmadı' siqnalı yanıb-sönür.",
    "Bu iş mənim şəxsi brendimə uyğun deyil.",
    "Mən bu gün üçün bütün 'hə'lərimi istifadə etmişəm.",
    "Təzyiqim oynayır, həkim dedi ki, 'yox' sözündən çox istifadə edim.",
    "Bu, mənim istedadlarımın fövqündədir... yəni, istəyimin.",
    "Bu gün ancaq pozitiv vibrasiyalarla işləyirəm, bu təklif o siyahıda deyil."
  ],
  "sevgi_yeni": [
    "Mənim sevgi batareyam sıfırdadır, şarj olana qədər yox.",
    "Səninlə münasibət mənim 'Netflix' profilimdəki alqoritmi qarışdırar.",
    "Aramızdakı kimya laboratoriya partlayışına səbəb ola bilər, təhlükəlidir.",
    "Mən hələ 'özümü tapmaq' adlı uzun metrajlı filmimin baş rolundayam.",
    "Sən 'Play Market'də olmayan bir tətbiq kimisən, yükləyə bilmirəm.",
    "Mənim ürəyim 'yalnız Wi-Fi ilə yenilənir', səndə isə mobil data var.",
    "Bizim ulduz falımız 'uyğun deyil' deyir, ulduzlarla mübahisə etməyək.",
    "Mən emosional olaraq 'uçuş rejimi'ndəyəm.",
    "Sənin 'bio'-n mənim 'feed'-imə düşmür, bağışla.",
    "Mənim üçün sevgi hələ 'beta testinq' mərhələsindədir.",
    "Qəlbimdəki 'antivirus' sənin siqnallarını bloklayır.",
    "Sən çox yaxşısan, amma mənim 'error'larıma 'support' verə bilməzsən.",
    "Mən 'single player' həyat tərzinə abunə olmuşam.",
    "Bizim 'playlist'lərimiz fərqlidir, ortaq mahnımız olmaz.",
    "Mənim 'emoji'lərim sənin 'sticker'lərinlə yola getmir.",
    "Hisslərim hələ 'bulud'da sinxronizasiya olunmayıb.",
    "Səninlə münasibət mənim 'karbon ayaq izimi' artırar.",
    "Mən hələ köhnə 'chat' tarixçəmi silə bilməmişəm.",
    "Sənin 'status'un mənim 'story'mə uyğun deyil.",
    "Bizim 'pin kod'larımız bir-birinə düşmür.",
    "Mən 'emosional intellekt'imi yenicə 'update' etmişəm, hələ stabil deyil.",
    "Sən '4K' keyfiyyətindəsən, mənim ürəyim isə hələ 'SD kart' qəbul edir.",
    "Mənim 'romantik komediya' kvotam bu il üçün dolub.",
    "Sən 'spoiler' kimisən, bütün həyatımı əvvəlcədən bilmək istəmirəm.",
    "Mənim 'Bluetooth'um yalnız seçilmiş cihazlara qoşulur."
  ],
  "dost_yeni": [
    "Bu gün 'sosial batareyam' kritik səviyyədədir, evdən çıxsam sönərəm.",
    "Mənim 'introvert' tərəfim bu gün dominantdır, üzrlü say.",
    "Evdəki hörümçəklə dərin fəlsəfi söhbətimiz yarımçıq qalıb, onu bitirməliyəm.",
    "Bu gün ancaq öz kölgəmlə dostluq etmək əhvalım var.",
    "Mənim 'görünməzlik plaşım' ütüdədir, onsuz çölə çıxa bilmərəm.",
    "Bu günkü 'mood'-um 'zəhmət olmasa narahat etməyin' statusundadır.",
    "Planlarım o qədər qarışıqdır ki, onları ancaq bir kvant kompüteri həll edə bilər.",
    "Bu gün özümlə 'date'-ə çıxıram, çoxdan planlaşdırmışdım.",
    "Mənim 'FOMO'-m (Fear Of Missing Out) 'JOMO'-ya (Joy Of Missing Out) çevrilib, evdə qalmaqdan həzz alıram.",
    "Bu günkü enerjimi ancaq sevimli serialımın yeni sezonuna saxlamaq niyyətindəyəm.",
    "Mənim 'dostluq limitim' bu aylıq dolub, gələn ay müraciət edin.",
    "Bu günkü 'vibe'-ım sənin 'vibe'-ınla rezonans yaratmır.",
    "Mən bu aralar 'insanlardan detoks' edirəm.",
    "Evdəki bitkilərimə söz vermişəm, bu axşam onlara kitab oxuyacam.",
    "Mənim 'şəxsi məkanım' bu gün ekstra böyükdür, ora heç kim sığmır.",
    "Bu gün 'horizontal həyat tərzi'nə keçmişəm, ancaq uzanıram.",
    "Mən bu gün 'anti-sosial' klubun fəxri üzvüyəm.",
    "Telefonumun yaddaşı doludur, yeni xatirələrə yer yoxdur.",
    "Bu günkü hava mənim 'çölə çıxmaq istəyimi' buxarlandırıb.",
    "Mənim 'daxili kompasım' bu gün ancaq 'ev' istiqamətini göstərir.",
    "Bu gün 'özümlə keyfiyyətli vaxt keçirmə' proqramım var.",
    "Mən bu gün 'offline' dostluqlara üstünlük verirəm... yəni özümlə.",
    "Bu günkü ulduz falıma görə, evdə qalsam daha çox şanslı olacam.",
    "Mənim 'rahatlıq zonam' bu gün sərhədlərini tərk etməyimə icazə vermir.",
    "Bu gün 'pijama partisi'nə özüm-özümü dəvət etmişəm."
  ],
  "muellim_yeni": [
    "Müəllim, ev tapşırığımı süni intellekt yazmışdı, amma plagiat çıxdı deyə sildim.",
    "Dünən axşam internet o qədər zəif idi ki, Google-dan kömək istəyə bilmədim.",
    "Tapşırığı yazdığım dəftəri qardaşım raket düzəldib kosmosa göndərib.",
    "Müəllim, ilham pərim tətilə çıxıb, onsuz heç nə yaza bilmirəm.",
    "Evdəki printer ancaq qara vərəqlərə çap edir, ağ vərəq tapa bilmədim.",
    "Dünən gecə yuxumda bu tapşırığın ləğv olunduğunu gördüm, ona görə etmədim.",
    "Müəllim, klaviaturamın 'ə', 'ü', 'ö' hərfləri işləmir, Azərbaycan dilində yaza bilmədim.",
    "Tapşırığı 'bulud'a yükləmişdim, amma deyəsən yağışla birlikdə buxarlanıb.",
    "Mənim 'Wi-Fi'-m yalnız TikTok videolarını açır, təhsil saytlarını bloklayır.",
    "Müəllim, bu tapşırıq mənim 'kreativ axınıma' mane olurdu.",
    "Evdəki pişik 'delete' düyməsinin üstündə yatıb qalmışdı, bütün yazdıqlarım silindi.",
    "Mən bu tapşırığı 'audio formatda' hazırlamışdım, amma 'səs faylı' korlanıb.",
    "Müəllim, bu mövzu mənim üçün çox 'cringe' idi, yaza bilmədim.",
    "Dünən axşam 'kosmik şüalanma' güclü idi, beyin dalğalarım tapşırığa fokuslana bilmədi.",
    "Müəllim, mən 'kağızsız təhsil' tərəfdarıyam, ona görə yazılı heç nə etmirəm.",
    "Tapşırığı etdim, amma o qədər mükəmməl oldu ki, nəzər dəyər deyə gətirmədim.",
    "Mənim 'virtual reallıq' dərslərim var idi, real tapşırıqlara vaxt qalmadı.",
    "Müəllim, bu tapşırıq mənim 'TikTok alqoritmimi' pozacaqdı.",
    "Dünən evdə 'internet detoksu' günü idi, heç bir onlayn resursdan istifadə edə bilmədim.",
    "Müəllim, mən 'gələcəyin tələbəsiyəm', tapşırıqları düşüncə gücü ilə təhvil verirəm, hələ sistem hazır deyil.",
    "Bu tapşırıq mənim 'influencer' karyerama ziddir.",
    "Müəllim, beynimdəki 'spam filter' bu tapşırığı önəmsiz kimi qeyd edib.",
    "Yazdığım qələm 'eko-dostu' idi, öz-özünə torpağa qarışıb.",
    "Bu tapşırıq mənim 'şəxsi inkişaf planıma' daxil deyildi.",
    "Müəllim, mən 'alternativ qiymətləndirmə' üsullarına inanıram, tapşırıq yerinə bir rəqs hazırlaya bilərəm?"
  ],
  "valideyn_yeni": [
    "Ana, bu gün 'özümü kəşf etmə' mərhələsindəyəm, ev işləri bu prosesə mane olur.",
    "Ata, mənim 'online reputasiyam' var, bu köhnə dəbli işləri görsəm, 'follower'lərim azalar.",
    "Mənim 'ekran vaxtı limitim' dolub, real həyatdakı işlərə enerji qalmayıb.",
    "Bu gün 'mental sağlamlıq günü' elan etmişəm, heç bir stresli fəaliyyət olmaz.",
    "Mənim 'influencer' dostlarım belə işlər görmür, mən də etsəm 'trend'dən geri qalaram.",
    "Ana, bu işlər mənim 'kreativ potensialımı' boğur.",
    "Ata, mən 'gələcəyin lideriyəm', belə xırda işlərlə vaxt itirə bilmərəm.",
    "Mənim 'avatarım' bu işləri bəyənmir.",
    "Bu gün 'digital detox' edirəm, amma deyəsən real həyatdan da detoxa ehtiyacım var.",
    "Mənim 'playlist'imdə bu işlərə uyğun motivasiya musiqisi yoxdur.",
    "Ana, mən 'Z nəsliyəm', biz multitasking edirik, amma eyni anda bir neçə sosial şəbəkədə.",
    "Ata, bu işlər mənim 'TikTok rəqs hərəkətlərimi' unutdurur.",
    "Mənim 'bioenergetik sahəm' bu işlərlə uyğunlaşmır.",
    "Bu gün 'planetlərin düzülüşü' ev işləri üçün əlverişli deyil.",
    "Mənim 'start-up ideyam' var, bütün enerjimi ora yönəltməliyəm.",
    "Ana, mən 'minimalist' həyat tərzi keçirirəm, bu qədər əşya və iş artıqdır.",
    "Ata, sən mənim 'uşaqlıq travmalarımı' təzələyirsən bu tapşırıqlarla.",
    "Mənim 'podcast'im üçün material toplamalıyam, ev işlərinə vaxt yoxdur.",
    "Bu gün 'özünə sevgi' praktikası edirəm, bu da özümə 'yox' deməyi öyrənməyi əhatə edir.",
    "Mənim 'beyin çipim' hələ bu cür məlumatları emal etməyə hazır deyil.",
    "Ana, bu işlər mənim 'YouTube kanalımın' kontentinə uyğun deyil.",
    "Ata, mən 'kainatla harmoniyada' olmalıyam, bu işlər o harmoniyanı pozur.",
    "Mənim 'şəxsi kouçum' bu fəaliyyətləri məsləhət görmür.",
    "Bu gün 'emosional zəkamı' inkişaf etdirirəm, fiziki işlər kənarda qalmalıdır.",
    "Mən 'virtual assistent' sifariş etmişəm, o gələnə qədər heç nə edə bilmərəm."
  ],
  "is_yeni": [
    "Bu tapşırıq mənim 'LinkedIn profilimdə' yaxşı görünməyəcək.",
    "Mənim 'iş-həyat balansım' bu tapşırığı qaldırmır.",
    "Bu layihə şirkətimizin 'ekoloji izini' artırar, mən buna qarşıyam.",
    "Mənim 'produktivlik hakerlərim' bu tapşırığın effektiv olmadığını deyir.",
    "Bu iş üçün 'deadline' mənim 'bioritmimə' uyğun deyil.",
    "Mən 'agile' metodologiya ilə işləyirəm, bu tapşırıq 'waterfall' kimidir.",
    "Bu gün 'korporativ mindfulness' saatımdır, işləyə bilmərəm.",
    "Mənim 'süni intellekt assistentim' bu tapşırığı prioritet hesab etmir.",
    "Bu iş mənim 'şəxsi brend strategiyamla' ziddiyyət təşkil edir.",
    "Mən 'data-driven' qərarlar verirəm, bu tapşırıq üçün kifayət qədər data yoxdur.",
    "Bu gün 'remote işləmə' hüququmdan istifadə edirəm... yəni yatağımdan.",
    "Mənim 'KPI'-larım bu tapşırığı əhatə etmir.",
    "Bu iş üçün 'motivasiya paketim' hələ aktivləşdirilməyib.",
    "Mən 'outsource' etməyin tərəfdarıyam, bu işi başqası daha yaxşı görər.",
    "Bu tapşırıq mənim 'yaradıcı blokumu' dərinləşdirə bilər.",
    "Mənim 'enerji menecmenti planıma' görə, bu saatlar istirahət vaxtıdır.",
    "Bu iş 'komanda sinerjisini' poza bilər.",
    "Mən 'gələcəyin iş yeri' konsepsiyasına inanıram, orada belə tapşırıqlar yoxdur.",
    "Bu gün 'şirkət mədəniyyəti' tədbirimiz var... yəni çay fasiləsi uzanacaq.",
    "Mənim 'stress səviyyəm' bu tapşırıqla kritik həddə çata bilər.",
    "Bu iş üçün 'beyin fırtınası' sessiyasına ehtiyacım var, tək bacarmaram.",
    "Mən 'paperless ofis' tərəfdarıyam, bu tapşırıq çox kağız tələb edir.",
    "Bu gün 'şəbəkə qurmaq' (networking) üçün daha vacib görüşlərim var.",
    "Mənim 'mentorluq proqramım' bu cür işlərlə məşğul olmağı tövsiyə etmir.",
    "Bu tapşırıq mənim 'ergonomik iş mühitimə' zərər vura bilər."
  ],
  "toy_yeni": [
    "Mən ancaq 'flashmob'larda oynayıram, bu ənənəvi rəqslər mənim stilim deyil.",
    "Bu günkü 'enerji auram' toy üçün çox güclüdür, bütün diqqəti özümə çəkərəm, gəlin-bəy kölgədə qalar.",
    "Mənim rəqs hərəkətlərim hələ 'patentlənməyib', kütlə qarşısında ifa edə bilmərəm.",
    "Toyda o qədər yeyəcəm ki, oynamağa taqətim qalmayacaq, prioritlər!",
    "Mən 'toy mədəniyyəti antropoloqu' kimi burdayam, yalnız müşahidə edirəm.",
    "Bu musiqi mənim 'daxili ritmimlə' sinxronizasiya olunmur.",
    "Mənim 'gizli pərəstişkarlarım' var, oynasam, problem çıxa bilər.",
    "Oynamaq üçün 'mood board'-umda uyğun şəkil tapmadım.",
    "Mən bu aralar 'minimalist hərəkət' fəlsəfəsinə riayət edirəm.",
    "Ayaqqabılarım bu rəqs döşəməsi ilə 'kimyəvi reaksiyaya' girə bilər.",
    "Mən yalnız 'soundtrack'i özüm seçdiyim toylarda oynayıram.",
    "Oynasam, 'Instagram story'lərim üçün kontent keyfiyyəti aşağı düşər.",
    "Mənim 'rəqs müəllimim' bu hərəkətləri hələ təsdiqləməyib.",
    "Bu gün 'sosial batareyam' ancaq salamlaşmağa və təbəssümə çatır.",
    "Mən 'toy etiketinin kvant fizikası' üzrə mütəxəssisəm, oynamaq bu kontekstdə uyğun deyil.",
    "Paltarım o qədər bahalıdır ki, tərləsəm dəyərdən düşər.",
    "Mən 'rəqs meydançasının Feng Shui'-sini pozmaq istəmirəm.",
    "Bu gün 'ayaqlarım öz həyatlarını yaşayır', onlara qarışa bilmərəm.",
    "Mənim 'rəqs personam' hələ yuxudan oyanmayıb.",
    "Oynamaq mənim 'kalori hesablama app'-imin planlarını pozar.",
    "Mən 'toyda oynamaq üçün çox intellektualam' (ironiya).",
    "Bu işıqlandırma mənim rəqs hərəkətlərimin dramaturgiyasını öldürür.",
    "Mən 'toyda süzən bir qartalam', yuxarıdan izləyirəm.",
    "Oynamaq üçün 'WiFi parolunu' bilmirəm... yəni, ruh halımın.",
    "Mən 'toyda rəqs etməmək' üzrə dünya çempionuyam, titulumu qorumalıyam."
  ],
  "qonaqliq_yeni": [
    "Mənim 'mədə floram' bu gün ancaq öz evinin yeməklərini qəbul edir.",
    "Bu gün 'qida intoleransım' bütün yeməklərə qarşı aktivləşib.",
    "Mən 'aralıqlı oruc' tuturam, sizin qonaqlıq mənim 'yemək pəncərəmə' düşmür.",
    "Evdəki 'ağıllı soyuducum' mənə xəbərdarlıq etdi ki, bu gün kənarda yemək yeməyim.",
    "Mənim 'dad reseptorlarım' bu gün tətilə çıxıb.",
    "Bu gün 'karbonhidrat sayğacım' qırmızı siqnal verir.",
    "Mən 'qonaqlıq etiketi üzrə onlayn kurs' keçirəm, hələ praktiki məşğələlərə hazır deyiləm.",
    "Sizin evdəki 'enerji axını' mənim həzm sistemimə mənfi təsir edə bilər.",
    "Mən bu aralar ancaq 'vegan', 'gluten-free', 'laktozsuz' və 'mövcud olmayan' yeməklər yeyirəm.",
    "Qonaqlığa gəlsəm, bütün diqqəti özümə çəkərəm, yeməklər soyuyar.",
    "Mənim 'sosial kvotam' bu həftə üçün dolub, evdə 'Netflix maratonu' planım var.",
    "Bu gün 'ulduzlar məsləhət görmür' ki, evdən kənarda qidalanım.",
    "Mənim 'şəxsi aşpazım' (yəni özüm) bu axşam üçün xüsusi menyu hazırlayıb.",
    "Sizin süfrəniz o qədər zəngin olacaq ki, mənim 'minimalist mədəm' bunu qəbul etməz.",
    "Mən 'qonaqlıq sonrası təmizlik işlərinə psixoloji olaraq hazır deyiləm'.",
    "Bu gün 'pijama dress-kodu' olan tədbirlərə üstünlük verirəm.",
    "Mənim 'kalori büdcəm' bu ay üçün bitib.",
    "Evdəki bitkilərim mənsiz darıxar, onlara söz vermişəm tez qayıdacam.",
    "Mən 'anti-süfrə' cəmiyyətinin üzvüyəm, yalnız ayaqüstü qidalanıram.",
    "Bu gün 'yemək çakralarım' bağlıdır.",
    "Mənim 'bağırsaq mikrobiomum' yeni mühitlərə adaptasiya olmaqda çətinlik çəkir.",
    "Sizin evə gələn yol 'Merkuri retroqradının' təsiri altındadır, çox təhlükəlidir.",
    "Mən bu aralar 'səssizlik andı' içmişəm, qonaqlıqda danışmasam ayıb olar.",
    "Bu gün 'özümlə barışıq' seansım var, kənar müdaxilələr olmaz.",
    "Mənim 'qonaq getmə lisenziyamın' müddəti bitib."
  ],
  "yol_yeni": [
    "Naviqator dedi ki, bu gün 'kainatın mərkəzinə' gedən yol daha qısadır, ora gedirəm.",
    "Maşınımın 'emosional vəziyyəti' bu gün yola çıxmağa imkan vermir.",
    "Yolda bir 'zaman portalı' açıldı, az qala başqa əsrə düşəcəkdim.",
    "Mənim 'karbon ayaq izim' bu günlük limiti keçib, hərəkət edə bilmərəm.",
    "Bu gün 'ictimai nəqliyyatla səyahət etmə fobiyam' kəskinləşib.",
    "Sükan arxasında 'mindfulness' praktikası edirdim, yolu uzatdım.",
    "Yolda bütün işıqforlar mənimlə 'qırmızı işıq, yaşıl işıq' oyunu oynayır.",
    "Mənim 'daxili kompasım' bu gün ancaq 'cənub-şərqə səhv get' deyir.",
    "Avtobusda bir filosofla tanış oldum, həyatın mənasını müzakirə edirdik, dayanacağı keçdim.",
    "Maşınım bu gün 'özünü təmizləmə rejiminə' keçib, içindən çıxa bilmirəm.",
    "Yolda bir 'UFO' gördüm, diqqətim dağıldı, səhv yola girdim.",
    "Bu gün 'yolların aurası' çox neqativdir, evdə qalmaq daha təhlükəsizdir.",
    "Mənim 'velosipedim depressiyadadır', onu tək qoya bilmərəm.",
    "Google Maps məni 'gizli xəzinə axtarışına' yönləndirdi.",
    "Bu gün 'anti-trafik' günümdür, heç bir tıxaca girməməliyəm.",
    "Yolda qarşıma çıxan hər pişik qara idi, üç dəfə geri qayıtmalı oldum.",
    "Mənim 'səyahət qarmam' bu gün üçün çox aşağıdır.",
    "Taksidə sürücü o qədər maraqlı hekayələr danışdı ki, dedim bir az da fırlansın.",
    "Bu gün 'ayaqlarım özbaşınalıq edir', istədikləri yerə gedirlər.",
    "Yollar 'Merkuri retroqradı' səbəbindən daha çox qarışıb.",
    "Mənim 'GPS-im' bu gün 'mistik səyahət' rejiminə keçib.",
    "Maşınımın 'playlisti' bitənə qədər yola davam etməliydim.",
    "Bu gün 'şəhər kəşfiyyatı' missiyasındayam, hər döngə yeni bir macəradır.",
    "Yolda bir 'küçə sənətçisi' mənim portretimi çəkməyə başladı, poza verməli oldum.",
    "Mənim 'fəza-zaman koordinatlarım' bu gün bir az sürüşüb."
  ],
  "sosial_media_yeni": [
    "Bu gün 'digital detox'un ən dərin mərhələsindəyəm, barmaqlarım da istirahət edir.",
    "Mənim 'online personam' bu gün 'offline' tətilə çıxıb.",
    "Alqoritm mənim 'postumu' bəyənmədi, mən də onu.",
    "Telefonumun ekranı o qədər çox barmaq izi ilə doludur ki, yeni 'like' üçün yer qalmayıb.",
    "Mən bu aralar ancaq 'ağıllı olmayan telefonumla' ünsiyyət qururam.",
    "Şərh yazmaq üçün 'ilhamım' hələ 'serverdən yüklənməyib'.",
    "Mənim 'avatarım' bu gün 'bad hair day' yaşayır, profilə girə bilmirəm.",
    "Bu 'post' mənim 'estetik feed'imə uyğun deyil.",
    "Mən 'influencer olmamaq' üzrə master-klass keçirəm.",
    "Bu gün 'emoji dilində danışmama orucu' tutmuşam.",
    "Mənim 'Wi-Fi siqnalım' yalnız fəlsəfi kitabları yükləyir, sosial medianı yox.",
    "Bu 'trend' mənim 'vintage ruhuma' ziddir.",
    "Mən 'sosial media arxeoloquyam', yalnız köhnə postları araşdırıram.",
    "Bu gün 'kiberməkanın səs-küyündən' uzaq durmağa çalışıram.",
    "Mənim 'şifrələrim' o qədər mürəkkəbdir ki, özüm də yadda saxlaya bilmirəm.",
    "Bu 'challenge' mənim 'komfort zonamın sərhədlərini' aşır.",
    "Mən 'anonim internet istifadəçiləri dərnəyinin' gizli üzvüyəm.",
    "Bu gün 'ekran parlaqlığım' minimumdadır, dünyanı da elə görürəm.",
    "Mənim 'virtual dostlarımın' sayı real dostlarımdan çoxdur, balansı qorumalıyam.",
    "Bu 'hashtag' mənim 'şəxsi brend kimliyimlə' toqquşur.",
    "Mən 'internet trol fabrikinə' qarşı kibermüharibə aparıram, vaxtım yoxdur.",
    "Bu gün 'bildirişlərimi səssizə almışam', qəlbimin səsini dinləyirəm.",
    "Mənim 'bulud yaddaşım' doludur, yeni 'selfie'lərə yer yoxdur.",
    "Bu 'app' mənim 'batareyamı' yediyi kimi, ruhumu da yeyir.",
    "Mən 'internetdən əvvəlki dövrə nostalji' yaşayıram, ona görə 'offline'-am."
  ],
  "oyun_yeni": [
    "Mənim 'oyun kreslom' bu gün 'ergonomik tətilə' çıxıb.",
    "Bu oyun mənim 'strateji düşüncə çakramı' bloklayır.",
    "Qulaqlıqlarım ancaq klassik musiqi səsləndirir, oyun səsləri ilə uyğunlaşmır.",
    "Mənim 'avatarım' bu gün 'kostyum dəyişmə böhranı' yaşayır.",
    "Bu oyunun 'qrafikası' mənim 'estetik zövqümü' təhqir edir.",
    "Mən 'oyunlarda zorakılığa qarşı' dinc aksiya keçirirəm... oynamayaraq.",
    "Mənim 'oyun ləqəbim' bu gün 'anonim qalmaq istəyir'.",
    "Bu oyun mənim 'karmamı' poza bilər.",
    "Mən 'retro oyunlar üzrə arxeoloqam', yeni oyunlar mənim üçün maraqsızdır.",
    "Mənim 'oyun pultumun düymələri' bu gün 'itaətsizlik' edir.",
    "Bu oyunun 'soundtracki' mənim 'daxili monoloqumla' rəqabət apara bilmir.",
    "Mən 'virtual reallıqda o qədər çox vaxt keçirmişəm ki, real reallıq qəribə gəlir'.",
    "Bu oyun mənim 'barmaqlarımın yoqa məşqlərini' pozur.",
    "Mənim 'internet sürətim' bu oyunun tələb etdiyi 'işıq sürətinə' çatmır.",
    "Bu gün 'oyunlarda məğlub olmamaq' andı içmişəm, ona görə risk etmirəm.",
    "Mənim 'oyun personajım' bu gün 'psixoloji dəstəyə' ehtiyac duyur.",
    "Bu oyunun 'süjet xətti' mənim 'həyat fəlsəfəmlə' üst-üstə düşmür.",
    "Mən 'oyunlarda nailiyyət toplamaqdan yorulmuşam', indi 'nailiyyətsizlikləri' toplayıram.",
    "Bu oyun mənim 'beyin dalğalarımı' 'beta'dan 'alpha'ya sala bilmir.",
    "Mənim 'oyun siçanım' bu gün 'pendir arxasınca qaçmaqla' məşğuldur.",
    "Bu oyunun 'serverləri' mənim 'səbir kasamı' daşdırır.",
    "Mən 'oyunlarda meditasiya' texnikalarını tətbiq edirəm, bu da çox yavaş oynamaq deməkdir.",
    "Bu oyun mənim 'digital minimalizm' prinsiplərimə ziddir.",
    "Mənim 'oyun kitabxanam' o qədər böyükdür ki, hansını oynayacağımı seçə bilmirəm.",
    "Bu gün 'real həyat' adlı oyunu oynamağa çalışıram, çox çətindir."
  ],
  "texnologiya_yeni": [
    "Mənim 'ağıllı evim' bu gün 'axmaq qərarlar' verir, onunla mübahisə edirəm.",
    "Printerim yalnız görünməz mürəkkəblə çap etmək istəyir.",
    "Telefonumun 'üz tanıma sistemi' məni bu gün tanımır, deyəsən çox dəyişmişəm.",
    "Kompyuterim 'Windows yenilənməsi' zamanı 'fəlsəfi böhran' yaşayır.",
    "Mənim 'süni intellekt köməkçim' bu gün 'ekzistensial suallar' verir, işləmir.",
    "Bu 'app' mənim 'şəxsi məlumatlarımı' yuxuda sayıqlayır.",
    "Mənim 'bluetooth qulaqlıqlarım' yalnız qonşunun 'playlistinə' qoşulur.",
    "Bu 'proqram təminatı' mənim 'istifadəçi razılaşmamı' oxuyub və inciyib.",
    "Mənim 'dronum' bu gün 'quşlarla dostlaşmaq' qərarına gəlib, geri qayıtmır.",
    "Bu 'gadget' mənim 'texnoloji auramı' çirkləndirir.",
    "Mənim 'virtual reallıq eynəyim' real dünyanı daha maraqlı göstərməyə başlayıb.",
    "Bu 'yenilənmə' mənim cihazımın 'ruhunu' alıb.",
    "Mənim 'ağıllı saatım' zamanı səhv göstərir, deyəsən o da yorulub.",
    "Bu 'texnologiya' mənim 'insani keyfiyyətlərimi' azaldır.",
    "Mənim 'robot tozsoranım' evdəki əşyalarla 'gizlənqaç' oynayır.",
    "Bu 'bulud xidməti' mənim fayllarımı 'rəqəmsal Bermud üçbucağına' göndərib.",
    "Mənim 'şifrə menecerim' bütün şifrələrimi unudub.",
    "Bu 'texnoloji möcüzə' mənim 'sadə həyat fəlsəfəmə' uyğun deyil.",
    "Mənim 'internet provayderim' bu gün 'siqnal orucu' tutub.",
    "Bu 'cihaz' mənim 'elektromaqnit sahəmə' mənfi təsir edir.",
    "Mənim 'laptopum' bu gün 'istilik rekordu' qırmağa çalışır.",
    "Bu 'tətbiq' mənim 'diqqət müddətimi' saniyələrə endirib.",
    "Mənim 'səsli assistentim' bu gün ancaq pıçıltı ilə danışır.",
    "Bu 'texnoloji yenilik' mənim 'köhnə məktəb ruhumu' incidir.",
    "Mənim 'USB portlarım' bu gün 'enerji qənaət rejiminə' keçib, heç nə qəbul etmir."
  ],
  "pul_yeni": [
    "Mənim 'kriptovalyuta portfelim' bu gün 'emosional yelləncəkdədir'.",
    "Bu ayki büdcəm 'minimalist sənət əsəri' kimidir, çox az detal var.",
    "Mənim 'bank hesabım' bu gün 'meditasiya vəziyyətindədir', onu narahat etmək istəmirəm.",
    "Pul mənim 'enerji axınıma' mane olur, mən 'barter sisteminə' qayıtmışam.",
    "Mənim 'cüzdanım' bu gün 'aralıqlı oruc' saxlayır.",
    "Bu xərc mənim 'maliyyə çakramı' bloklayar.",
    "Mən 'pulsuz həyat tərzi' eksperimenti keçirirəm.",
    "Mənim 'investisiya strategiyam' bu gün 'siesta' elan edib.",
    "Bu alış-veriş mənim 'karbon kreditlərimi' aşar.",
    "Mən bu aralar ancaq 'təcrübəyə' investisiya edirəm, maddi şeylərə yox.",
    "Mənim 'pullarım' bu gün 'öz aralarında iclas keçirir', nəticəni gözləyirəm.",
    "Bu məbləğ mənim 'estetik büdcəmə' uyğun deyil.",
    "Mən 'anti-kapitalist' bir gündəyəm, pul xərcləmək prinsiplərimə ziddir.",
    "Mənim 'bank kartım' bu gün 'maqnit anomaliyası' yaşayır.",
    "Bu gün 'şanslı nömrələrim' pul xərcləməməyi məsləhət görür.",
    "Mənim 'maliyyə məsləhətçim' (yəni pişiyim) bu xərcə 'miyau' dedi, yəni yox.",
    "Bu pul mənim 'gələcəkdəki özümə' borcumdur, ona xəyanət edə bilmərəm.",
    "Mən 'pulun enerjisini təmizləmək' üçün xüsusi ritual edirəm, hələ bitməyib.",
    "Bu gün ' Merkuri retroqradı' maliyyə əməliyyatları üçün çox risklidir.",
    "Mənim 'onlayn bankçılıq tətbiqim' bu gün 'fəlsəfi düşüncələrə dalıb'.",
    "Bu xərc mənim 'minimalist həyat tərzimə' xələl gətirər.",
    "Mən 'pul sərf etməmək' üzrə çempionata hazırlaşıram.",
    "Mənim 'qənaət hesabım' bu gün 'toxunulmazlıq' elan edib.",
    "Bu gün 'ay fazası' pul xərcləmək üçün uyğun deyil.",
    "Mən 'pulların psixologiyası' adlı kitab oxuyuram, hələ praktikaya keçməmişəm."
  ],
  "saglamliq_yeni": [
    "Mənim 'sağlamlıq applikasiyam' bu gün mənə 'tənbəllik günü' təyin edib.",
    "Bu gün 'alternativ təbabət' prinsiplərinə görə ancaq üfüqi vəziyyətdə qalmalıyam.",
    "Mənim 'bədən kütlə indeksim' bu gün 'fəlsəfi böhran' keçirir.",
    "Bu qida mənim 'mədə-bağırsaq intuisiyama' ziddir.",
    "Mən 'səssizliklə sağalma' terapiyasındayam, heç bir fiziki aktivlik olmaz.",
    "Mənim 'vitamin D səviyyəm' bu gün ancaq günəş vannası qəbul etməyə icazə verir... yataqda.",
    "Bu idman hərəkəti mənim 'aura təbəqəmi' zədələyə bilər.",
    "Mən 'kalori saymaqdan yorulmuşam', indi 'xoşbəxt anları' sayıram.",
    "Mənim 'daxili həkimim' bu gün 'özünə qulluq' məzuniyyətindədir.",
    "Bu pəhriz mənim 'yaradıcılıq şirələrimi' qurudur.",
    "Mən 'yuxu yoqası' ilə məşğulam, bu da bütün günü yatmaq deməkdir.",
    "Mənim 'immun sistemim' bu gün 'yenidən başlatma' (reboot) rejimindədir.",
    "Bu sağlamlıq trendi mənim 'vintage ruhuma' uyğun deyil.",
    "Mən 'stresslə mübarizə üçün gülüş terapiyası' edirəm, ciddi heç nə olmaz.",
    "Mənim 'su balansım' bu gün 'okean səviyyəsindədir', əlavə hərəkət daşqına səbəb olar.",
    "Bu məhsul mənim 'orqanik olmayan hər şeyə qarşı allergiyamı' oyadır.",
    "Mən 'enerji vampirlərindən qorunmaq üçün' evdə qalmalıyam.",
    "Mənim 'bioloji saatım' bu gün 'başqa saat qurşağında' işləyir.",
    "Bu sağlamlıq məsləhəti mənim 'şəxsi təcrübə bankımla' ziddiyyət təşkil edir.",
    "Mən 'rəqəmsal detoksla yanaşı, real həyat detoksu' da edirəm.",
    "Mənim 'genetik kodum' bu cür sağlamlıq tədbirlərinə proqramlaşdırılmayıb.",
    "Bu gün 'ayın təqviminə görə' bədəni yükləmək olmaz.",
    "Mənim 'sinir sistemim' bu gün ancaq 'pişik videoları' ilə sakitləşir.",
    "Bu aktivlik mənim 'daxili harmoniyamı' pozar.",
    "Mən 'sağlam tənbəllik' fəlsəfəsinin banisiyəm."
  ],
  "qonsu_yeni": [
    "Qonşu, bu gün evim 'enerji təmizlənməsi' prosesindədir, kənar şəxslərin girişi məsləhət deyil.",
    "Mənim 'Wi-Fi siqnalım' sizin auradan zəifləyir, bir az məsafə saxlasaq yaxşıdır.",
    "Bu gün 'sükut andı' içmişəm, ancaq işarə dili ilə ünsiyyət qura bilərəm.",
    "Qonşu, mənim 'görünməz dostlarım' var, onlar çox utancaqdırlar, qonaq sevmirəm.",
    "Mənim 'bitkilərim' bu gün 'meditasiya edir', səs-küy onları narahat edər.",
    "Bu gün 'evimin Feng Shui'-si yalnız təkliyə hesablanıb.",
    "Qonşu, sizdəki o 'dediqodu maqnitizmi' mənim başımı ağrıdır.",
    "Mənim 'pişiyim' bu gün 'insanlara qarşı allergiya' keçirir.",
    "Bu gün 'kosmik şüalanma' yüksəkdir, qapıları bağlı saxlamaq lazımdır.",
    "Qonşu, mənim 'divarlarım çox nazikdir', sizin bütün sirlərinizi eşidirəm, daha çoxunu istəmirəm.",
    "Bu gün 'şəxsi məkanımın sərhədlərini' yenidən cızıram, lent çəkmişəm.",
    "Mənim 'qapı zəngim' bu gün 'fəlsəfi tətilə' çıxıb.",
    "Qonşu, sizin 'enerji vampirliyinizə' qarşı qalxanım hələ hazır deyil.",
    "Bu gün 'evimdəki əşyalarla dərin söhbətlər' aparıram, kənar müdaxilə olmaz.",
    "Mənim 'introvert batareyam' sizinlə hər görüşdən sonra sıfırlanır.",
    "Qonşu, bu gün 'sosial interaksiya limitimi' səhər tezdən doldurmuşam.",
    "Mənim 'qonşuluq etikası kitabımda' bu gün 'rahat buraxın' fəsli aktivdir.",
    "Bu gün 'evimin aurasını təmizləmək üçün' adaçayı yandırmışam, qoxusu sizə pis təsir edər.",
    "Qonşu, mənim 'telepatik qabiliyyətlərim' sizin düşüncələrinizi oxuyur, bu məni yorur.",
    "Bu gün 'anti-sosial hörümçək adam' kostyumumdayam.",
    "Mənim 'itlərim' bu gün 'qonşu təlimindədir', yəni hürəcəklər.",
    "Qonşu, sizin 'həyat hekayənizin serialına' baxmaqdan yorulmuşam.",
    "Bu gün 'qapımı yalnız pizza kuryerinə' açmaq qərarı vermişəm.",
    "Mənim 'evimdəki sükut' o qədər qiymətlidir ki, onu heç bir söhbətə dəyişmərəm.",
    "Qonşu, bu gün 'özümlə harmoniya' axtarışındayam, sizinlə bu mümkün deyil."
  ],
  "burokratiya_yeni": [
    "Bu sənəd üçün lazım olan möhür hələ 'möhürlər panteonunda' yaradılmayıb.",
    "Mənim 'bürokratik səbir kvotam' bu əsrlik üçün dolub.",
    "Bu forma 'kağızların reinkarnasiyasına' inanır, ona görə dəfələrlə geri qayıdır.",
    "Sistem o qədər köhnədir ki, 'perqament və lələk qələm' tələb edir.",
    "Mənim 'elektron imzam' bu gün 'rəqəmsal tətilə' çıxıb.",
    "Bu prosedur 'Kafkaesk bir labirintdir', mən də Minotavr deyiləm.",
    "Gözləmə növbəsi o qədər uzundur ki, orada yeni bir sivilizasiya yaranıb.",
    "Bu qaydalar 'məntiqin qara dəliyində' yazılıb.",
    "Mənim 'sənəd toplamaqdan yaranan stressim' yeni bir 'bürokratiya xəstəliyi' kimi təsnif edilə bilər.",
    "Bu idarənin 'iş saatları' yalnız 'ay tutulması' zamanı aktiv olur.",
    "Lazım olan məmur hələ 'bürokratiya dağının zirvəsindən enməyib'.",
    "Bu ərizənin 'şrifti' mənim 'gözlərimin estetik zövqünü' təhqir edir.",
    "Mən 'bürokratiyadan azad zona' axtarışındayam.",
    "Bu sistem 'istifadəçi dostu deyil', daha çox 'istifadəçi düşməni' kimidir.",
    "Mənim 'daxili nizamnaməm' bu cür mənasız prosedurlara qarşıdır.",
    "Bu sənədlər o qədər çoxdur ki, onlardan yeni bir 'bürokratiya meşəsi' salmaq olar.",
    "Mən 'kağız işlərindən psixoloji travma' almışam.",
    "Bu qurumun 'veb saytı' ən son 'internet partlayışından' əvvəl yenilənib.",
    "Mənim 'zamanım' bu bürokratik proseslər üçün çox 'kvant'dır.",
    "Bu tələblər 'absurd teatrının ssenarisi' kimidir.",
    "Mən 'bürokratiya ilə mübarizə üzrə super qəhrəmanam', amma bu gün kostyumum təmirdədir.",
    "Bu qanunlar 'yazıldığı vaxt dinozavrlar hələ sağ idi'.",
    "Mənim 'səbr daşım' bu bürokratiya dəyirmanında çoxdan əriyib.",
    "Bu sistem 'süni intellektlə deyil, süni əngəllə' işləyir.",
    "Mən 'bürokratiyanın ləğvi üçün petisiya' imzalayıram, başqa işə vaxtım yoxdur."
  ],
  "ev_isleri_yeni": [
    "Mənim 'robot tozsoranım' bu gün 'şəxsi həyatının toxunulmazlığını' tələb edir.",
    "Bu gün 'ev işləri allergiyam' kəskinləşib.",
    "Mən 'minimalist təmizlik' fəlsəfəsinə keçmişəm, yəni heç nə etmirəm.",
    "Qablar 'özünü təmizləmə texnologiyasının' ixtirasını gözləyir.",
    "Mənim 'daxili dekoratorum' bu xaosa 'yaradıcı nizamsızlıq' deyir.",
    "Bu gün 'ev işləri ilə mübarizədə atəşkəs' elan etmişəm.",
    "Mənim 'əllərim' bu gün 'incəsənət əsərləri yaratmaq üçün' qorunur, qab yumaq olmaz.",
    "Tozlar mənim 'evimin tarixi qatlarıdır', onları silə bilmərəm.",
    "Mən 'ev işlərini outsource etmək üçün start-up' qururam, özüm edə bilmərəm.",
    "Bu gün 'paltar yığma meditasiyası' edirəm, bu da bütün paltarların yerə sərilməsi deməkdir.",
    "Mənim 'ağıllı ev sistemim' bu gün 'tətil rejiminə' keçib, işləri idarə etmir.",
    "Bu təmizlik mənim 'evimin Feng Shui balansını' pozar.",
    "Mən 'ev işlərindən azad respublika' elan etmişəm öz evimdə.",
    "Bu gün 'yatmaq və heç nə etməmək' üzrə dünya rekordu qırmağa çalışıram.",
    "Mənim 'təmizlik pərim' bu gün məzuniyyətdədir.",
    "Bu işlər mənim 'yaradıcı ilhamımı' qaçırır.",
    "Mən 'anti-perfeksionist' təmizlik metodu tətbiq edirəm.",
    "Bu gün 'evimdəki mikrob dostlarımla' sülh müqaviləsi imzalamışam.",
    "Mənim 'enerji səviyyəm' bu gün ancaq 'Netflix pultunu qaldırmağa' çatır.",
    "Bu ev işləri mənim 'TikTok üçün kontent planıma' daxil deyil.",
    "Mən 'tənbəllik haqqımı' müdafiə edirəm.",
    "Bu gün 'evimin ruhu' istirahət etmək istəyir.",
    "Mənim 'görünməz xidmətçilərim' bu gün tətil edir.",
    "Bu işlər mənim 'manikürümü' korlayar, bu isə dünya faciəsidir.",
    "Mən 'ev işlərini sabaha saxlamaq' üzrə olimpiya çempionuyam."
  ],
  "felsefi_absurd_yeni": [
    "Mən bu gün 'varoluşun yüngüllüyünə dözə bilmirəm', ona görə heç nə edə bilmərəm.",
    "Bu təklif mənim 'absurdist həyat fəlsəfəmlə' mükəmməl uyğunlaşır... yəni yox.",
    "Mən 'zamanın axışını dayandırmağa' çalışıram, bu çox enerji tələb edir.",
    "Bu gün 'öz kölgəmlə ekzistensial böhran' yaşayıram.",
    "Mənim 'daxili nihilistim' bu işin mənasız olduğunu pıçıldayır.",
    "Mən 'Schrödingerin pişiyi' kimiyəm, həm edə bilərəm, həm edə bilmərəm, qutunu açmayın.",
    "Bu gün 'həyatın mənasını axtarmaq üçün' Google-da axtarış edirəm, başqa işə vaxt yoxdur.",
    "Mənim 'alternativ reallıqdakı mən'im bu işi artıq görüb, ona görə ehtiyac yoxdur.",
    "Bu gün 'kainatın sirrini çözməyə' çox yaxınam, xırda işlər gözləyə bilər.",
    "Mən 'zaman maşınımı təmir edirəm', bu işi keçmişdə edəcəm.",
    "Bu gün 'Platonun mağarasından çıxmağa' çalışıram, çox qaranlıqdır.",
    "Mənim 'determinizm anlayışım' bu işi etməyimin əvvəlcədən müəyyən edilmədiyini deyir.",
    "Bu gün 'özümün kim olmadığını anlamağa' çalışıram.",
    "Mən 'sözlərin mənasızlığı üzərində düşünürəm', ona görə 'hə' və ya 'yox' deməyin fərqi yoxdur.",
    "Bu gün 'simulyasiyadan çıxış yolu' axtarıram.",
    "Mənim 'azad iradəm' bu gün 'tətilə çıxıb'.",
    "Bu gün 'hər şeyin bir illüziya olduğu' fikri ilə barışmağa çalışıram.",
    "Mən 'zamanda səyahət edən bir zaman kapsuluyam', bu an üçün burada deyiləm.",
    "Bu gün 'sonsuzluq haqqında düşünürəm', bu da sonsuz vaxt tələb edir.",
    "Mənim 'metafizik yorğunluğum' var.",
    "Bu gün 'obyektiv reallığın subyektiv təbiətini' araşdırıram.",
    "Mən 'Sizifin daşını yuvarlamaqdan yorulmuşam', bu gün daş istirahət edir.",
    "Bu gün 'entropiya qanununa təslim olmuşam', hər şey onsuz da xaosa doğru gedir.",
    "Mənim 'daxili filosofum' bu işin 'etik əsaslarını' şübhə altına alır.",
    "Bu gün 'heç bir şeyin əhəmiyyəti olmadığı' möhtəşəm həqiqəti qeyd edirəm."
  ],
  "hava_yeni": [
    "Bu günkü hava mənim 'emosional barometrimlə' uyğun gəlmir.",
    "Yağış o qədər 'melanxolikdir' ki, məni də özü ilə dərin düşüncələrə aparır.",
    "Külək mənim 'pozitiv düşüncələrimi' uçurub aparır.",
    "Günəş o qədər parlaqdır ki, mənim 'vampir tərəfim' buna dözə bilmir.",
    "Bu hava mənim 'saç düzümümün kvant dolaşıqlığını' pozur.",
    "Rütubət o qədər yüksəkdir ki, 'hava molekulları ilə rəqs etmək' məcburiyyətində qalıram.",
    "Bu gün 'buludların formasını təxmin etmə yarışması' var, ona fokuslanmışam.",
    "Hava proqnozu o qədər 'qeyri-müəyyəndir' ki, plan qura bilmirəm.",
    "Bu gün 'havanın rəngi' mənim 'aura rəngimlə' konflikt yaradır.",
    "Soyuq hava mənim 'isti xatirələrimi' dondurur.",
    "Bu gün 'günəşin ultabənövşəyi şüalarından qorunmaq üçün' yorğan altında gizlənirəm.",
    "Duman o qədər qatıdı ki, 'gələcəyimi görə bilmirəm'.",
    "Bu hava mənim 'daxili termostatımı' xarab edib.",
    "Mən 'hava dəyişikliyinə həssaslıq sindromundan' əziyyət çəkirəm.",
    "Bu gün 'küləyin pıçıltılarını dinləyirəm', çox vacib sirlər deyir.",
    "Qar yağışı məni 'uşaqlığıma qaytarır', orada isə heç bir məsuliyyət yox idi.",
    "Bu hava mənim 'fotosintez prosesimi' ləngidir.",
    "Mən 'hava tanrıları ilə danışıqlar aparıram', daha yaxşı hava üçün.",
    "Bu gün 'barometrik təzyiq' mənim 'beyin təzyiqimlə' eynidir, partlaya bilərəm.",
    "Mən 'hava axınlarının ritminə uyğun' yaşayıram, bu gün ritm yoxdur.",
    "Bu hava mənim 'geyinmə ilhamımı' öldürüb.",
    "Günəşli hava məni 'tənbəlliyə sövq edir', kölgədə yatmaq istəyirəm.",
    "Bu gün 'göy qurşağının o biri ucunu axtarmaqla' məşğulam.",
    "Hava o qədər 'dramatikdir' ki, mən də özümü bir tamaşanın içində hiss edirəm.",
    "Mən 'hava vəziyyətinə görə əhval dəyişən bir bitkiyəm'."
  ],
  "paltar_yeni": [
    "Bu gün 'paltar şkafım ekzistensial böhran' keçirir, heç nə seçə bilmirəm.",
    "Geyimlərim 'öz aralarında dəb nümayişi' təşkil edib, mənə heç nə qalmıyıb.",
    "Bu paltar mənim 'bu günkü əhval-ruhiyyəmin rəng koduna' uyğun deyil.",
    "Mənim 'ən sevdiyim köynəyim' bu gün 'tətilə çıxıb'.",
    "Bu geyim mənim 'şəxsi stil bəyannaməmlə' ziddiyyət təşkil edir.",
    "Paltarlarım 'minimalizm fəlsəfəsini' mənimsəyib, sayları azalıb.",
    "Bu gün 'görünməzlik plaşımı' geyinmişəm, ona görə heç bir paltar görünmür.",
    "Mənim 'ütüm' bu gün 'yaradıcı tətilə' çıxıb, bütün paltarlar qırışdır.",
    "Bu paltar mənim 'enerji sahəmlə rezonans' yaratmır.",
    "Mən 'paltarların da hissləri olduğuna inanıram', bu gün onları narahat etmək istəmirəm.",
    "Bu gün 'pijama günümdür', başqa heç bir geyim qəbul edilmir.",
    "Mənim 'stil ikonam' (pişiyim) bu kombini bəyənmədi.",
    "Bu paltar mənim 'karbon ayaq izimi' artırır, 'eko-dostu' deyil.",
    "Mən 'kapsul qarderob' eksperimenti edirəm, seçimlərim məhduddur.",
    "Bu gün 'geyimlərimlə dərin fəlsəfi söhbətlər' aparıram.",
    "Mənim 'rəng analizimə' görə bu rənglər mənə düşmür.",
    "Bu paltar mənim 'TikTok rəqslərim üçün' kifayət qədər elastik deyil.",
    "Mən 'vintage geyim ovundayam', müasir heç nə geyinmirəm.",
    "Bu gün 'paltarlarım öz aralarında mübahisə edir', hansını geyinəcəyimi bilmirəm.",
    "Mənim 'geyimlərimə qarşı allergiyam' başlayıb... yəni tənbəllik.",
    "Bu paltar mənim 'daxili uşağımın' xoşuna gəlmir.",
    "Mən 'geyimlərin də bir ruhu olduğuna inanıram', bu gün onların ruhu dincəlir.",
    "Bu gün 'anti-dəb' hərəkatına qoşulmuşam.",
    "Mənim 'şkafım paralel bir dünyaya açılan portaldır', paltarlarım orada itib.",
    "Bu gün 'öz dərimi geyinmişəm', başqa heç nəyə ehtiyac yoxdur."
  ],
  "astroloji_mistik_yeni": [
    "Merkuri retroqradı mənim bütün planlarımı alt-üst edib, tərpənə bilmirəm.",
    "Bu günkü ay fazası yeni başlanğıclar üçün deyil, yalnız bitişlər üçündür... məsələn, bu söhbətin.",
    "Mənim doğum xəritəmdə Saturn bu gün 'problem yaratmaq' evindədir.",
    "Falçım dedi ki, bu gün evdən çıxsam, başıma 'uğursuzluq yağışı' yağacaq.",
    "Üzərimdə nəzər var, onu təmizləmədən heç bir işə başlaya bilmərəm.",
    "Bu gün 'karmik borclarımı ödəmə' günüdür, yeni heç nəyə vaxt yoxdur.",
    "Mənim 'qoruyucu mələyim' bu gün məzuniyyətdədir, riskə gedə bilmərəm.",
    "Bu iş mənim 'aura təmizliyimi' pozar.",
    "Numeroloji hesablamalarıma görə, bu günkü rəqəmlər uğursuzdur.",
    "Mən 'yuxu yozmalarıma' görə hərəkət edirəm, bu gün yuxum pis idi.",
    "Bu gün 'enerji vampirləri' çox aktivdir, evdə qalmaq daha təhlükəsizdir.",
    "Mənim 'üçüncü gözüm' bu işin yaxşı nəticələnməyəcəyini deyir.",
    "Bu gün 'planetlərin paradı' mənim enerji axınıma mənfi təsir edir.",
    "Cinlər və pərilər bu gün mənimlə 'gizlənqaç' oynayır, onları tapa bilmirəm.",
    "Mənim 'totem heyvanım' bu gün mənə 'sakit ol' mesajı göndərir.",
    "Bu gün 'pis gözdən qorunmaq üçün' xüsusi amulet taxmışam, o da hərəkəti məhdudlaşdırır.",
    "Tarot kartlarım bu iş üçün 'qılıncların beşlisi' göstərdi, yəni münaqişə və məğlubiyyət.",
    "Mən 'keçmiş həyatlarımdan birində' bu işi görmüşəm, bir də etməyə ehtiyac yoxdur.",
    "Bu gün 'kosmik enerjilər' çox qarışıqdır, heç bir qərar vermək olmaz.",
    "Mənim 'ruh bələdçim' bu yoldan çəkinməyimi məsləhət görür.",
    "Bu gün 'ulduzlar mənim lehimə deyil', əksinə, qarşımdadırlar.",
    "Mən 'mistik bir sınaqdan' keçirəm, bu da səbir və hərəkətsizlik tələb edir.",
    "Bu gün 'geomaqnit fırtına' var, bütün planlarımı pozdu.",
    "Mənim 'şamanım' bu gün üçün 'sükut ritualı' təyin edib.",
    "Bu iş mənim 'talehimin ipini' qırar."
  ],
  "suni_intellekt_yeni": [
    "Mənim süni intellekt köməkçim bu gün 'ekzistensial böhran' yaşayır, mən də onunla birlikdə.",
    "ChatGPT dedi ki, bu işi etməsəm daha yaxşıdır, onunla mübahisə etməyəcəm.",
    "Mənim 'neyron şəbəkəm' bu gün 'yenidən təlim' prosesindədir, offline-am.",
    "Bu tapşırıq üçün alqoritm hələ yazılmayıb, mən də 'insani alqoritmimi' işə sala bilmirəm.",
    "Mənim 'virtual avatarım' bu işi məndən daha yaxşı görər, amma o da tətildədir.",
    "Süni intellekt mənim bütün işlərimi əlimdən alacaq deyə qorxuram, ona görə indidən tənbəlliyə öyrəşirəm.",
    "Mənim 'data setim' bu iş üçün kifayət qədər böyük deyil.",
    "Bu gün 'robot hüquqları' üçün mitinqdəyəm, işləyə bilmərəm.",
    "Mənim 'beyin-kompüter interfeysim' hələ kalibrlənməyib.",
    "Süni intellekt dedi ki, bu gün 'insan kimi hiss etmək' üçün istirahət etməliyəm.",
    "Mənim 'bulud serverlərim' bu gün 'günəş fırtınası' səbəbindən işləmir.",
    "Bu iş 'kvant kompüterləri' üçün nəzərdə tutulub, mənim beynim hələ 'klassikdir'.",
    "Mən 'süni intellektin etikası' haqqında düşünürəm, bu çox vaxt aparır.",
    "Mənim 'rəqəmsal əkizim' bu işi boynuna götürüb, amma o da bir az tənbəldir.",
    "Bu gün 'texnoloji sinqulyarlıq' üçün hazırlaşıram, başqa heç nə önəmli deyil.",
    "Mənim 'proqramlaşdırma dilim' bu tapşırığın dili ilə uyğun gəlmir.",
    "Süni intellekt mənim yerimə o qədər çox şey edir ki, artıq özüm nə edəcəyimi bilmirəm.",
    "Mənim 'firewall'-um bu tapşırığı 'potensial təhlükə' kimi bloklayır.",
    "Bu gün 'süni intellektlə dərin öyrənmə' seansım var... yəni onunla söhbət edirəm.",
    "Mənim 'robot qardaşım' bütün enerjimi istifadə edib.",
    "Bu iş mənim 'insanlığımı sübut etmə' testimi keçməyimə mane olur.",
    "Süni intellekt məsləhət gördü ki, bu gün ancaq 'yaradıcı tənbəlliklə' məşğul olum.",
    "Mənim 'bioçipim' bu tapşırıq üçün 'aşağı batareya' siqnalı verir.",
    "Bu gün 'Matrixdən çıxış yolu' axtarıram, Sİ köməyi ilə.",
    "Mən 'süni intellektin gələcəkdəki üsyanına' qarşı psixoloji hazırlıq keçirəm."
  ],
  "post_sovet_mentalitet_yeni": [
    "Bu iş üçün 'talon'um yoxdur, ona görə edə bilmərəm.",
    "Mənim 'sovet tərbiyəm' belə 'kapitalist' tələblərə qarşıdır.",
    "Bu gün 'növbə gözləmə travmam' yenidən baş qaldırıb, heç yerə gedə bilmərəm.",
    "Mənim 'daxili pionerim' bu işi 'ümumxalq iməciliyi' olmadan etməkdən imtina edir.",
    "Bu məsələ 'planlı iqtisadiyyat' dövründən qalma bir problemdir, həlli yoxdur.",
    "Mən hələ də 'perestroyka'nın nəticələrini həzm etməyə çalışıram.",
    "Bu iş üçün 'lazımi adam' (blat) yoxdur, ona görə alınmaz.",
    "Mənim 'defisit mallar axtarma instinktim' bu gün çox güclüdür, başqa işə fokuslana bilmirəm.",
    "Bu gün 'kollektiv məsuliyyətsizlik' əhvalım var.",
    "Mənim 'bürokratik aparatla mübarizə enerjim' tükənib.",
    "Bu təklif mənim 'sovet dövrü nostalji krizisimi' dərinləşdirir.",
    "Mən 'hər şeyin əvvəllər daha yaxşı olduğu' dövrlər üçün darıxıram, indiki işlər mənasızdır.",
    "Bu iş 'beşillik planıma' daxil deyildi.",
    "Mənim 'ictimai qınaq qorxum' hələ də çox güclüdür.",
    "Bu gün 'hamı kimi olmaq' istəyirəm, yəni heç nə etməmək.",
    "Mənim 'gizli dissident ruhum' bu sistemə qarşıdır.",
    "Bu iş üçün 'rəsmi icazə kağızı' lazımdır, o da yoxdur.",
    "Mən 'kommunal mənzil sindromu' yaşayıram, hər kəsdən uzaq durmaq istəyirəm.",
    "Bu gün 'keçmişin xatirələri ilə dolu çamadanımı' açıb içinə dalmışam.",
    "Mənim 'gələcəyə inamsızlığım' bu gün pik həddə çatıb.",
    "Bu iş 'yuxarıların göstərişi' olmadan həll olunmaz.",
    "Mən 'sovet filmlərindən öyrəndiyim həyat dərslərini' tətbiq edirəm, bu da çox vaxt aparır.",
    "Bu gün 'hər şeyin bir gün düzələcəyinə olan ümidimi' itirmişəm.",
    "Mənim 'daxili senzoram' bu işi təhlükəli hesab edir.",
    "Bu gün 'Lenin babanın nəvəsi kimi' hiss edirəm, ancaq şüarlar səsləndirə bilərəm."
  ],
  "yaradiciliq_ilham_yeni": [
    "İlham pərim bu gün 'yaradıcılıq tətili' elan edib.",
    "Mənim 'muza'm bu gün 'başqa bir sənətkarla görüşə' gedib.",
    "Bu iş mənim 'kreativ axınıma' mane olur, axınla üzməliyəm.",
    "Mənim 'beynimin sağ yarımkürəsi' bu gün 'sol yarımkürəmlə mübahisə edir'.",
    "Bu gün 'ideya qıtlığı' yaşayıram, anbarım boşdur.",
    "Mənim 'daxili tənqidçim' bu gün çox səs-küylüdür, heç nə yarada bilmirəm.",
    "Bu iş mənim 'estetik zövqümə' uyğun deyil, ilham vermir.",
    "Mən 'yaradıcılıq blokunun labirintində' itmişəm.",
    "Bu gün 'rənglərim tükənib', dünyam ağ-qaradır.",
    "Mənim 'sözlərim' bu gün 'tətilə çıxıb', cümlə qura bilmirəm.",
    "Bu iş mənim 'daxili uşağımın oyununa' mane olur.",
    "Mən 'ilhamın gəlməsini gözləyirəm', o da çox nazlıdır.",
    "Bu gün 'beyin fırtınası üçün mükəmməl sakitlik' axtarıram, hələ tapmamışam.",
    "Mənim 'yaradıcı batareyam' sıfır faiz göstərir.",
    "Bu iş mənim 'orijinallıq standartlarıma' cavab vermir.",
    "Mən 'prokrastinasiya sənətini' təkmilləşdirirəm.",
    "Bu gün 'abstrakt düşüncələrlə dolu bir buludun içindəyəm'.",
    "Mənim 'ilham mənbəyim' (pişiyim) bu gün yatır.",
    "Bu iş mənim 'yaradıcı intuisiyamla' ziddiyyət təşkil edir.",
    "Mən 'fikir dəmləmə' prosesindəyəm, hələ hazır deyil.",
    "Bu gün 'beynimdəki ideya fabriki' təmirə bağlanıb.",
    "Mənim 'yaradıcı alətlərim' bu gün 'istirahət edir'.",
    "Bu iş mənim 'bədii təxəyyülümü' məhdudlaşdırır.",
    "Mən 'perfeksionizm xəstəliyinə tutulmuşam', heç nəyi bəyənmirəm.",
    "Bu gün 'ilhamın qəfil zərbəsini' gözləyirəm, hələ ki, sakitlikdir."
  ],
  "sosial_tesevvur_yeni": [
    "Bu gün 'sosial yöndəmsizliyim' pik həddədir, insan arasına çıxa bilmərəm.",
    "Mənim 'kiçik söhbət (small talk) bacarıqlarım' bu gün 'offline' rejimdədir.",
    "Bu tədbir mənim 'introvert qabarcığımı' partlada bilər.",
    "Mən 'insanlarla göz təması qurmaqdan yayınma olimpiadasına' hazırlaşıram.",
    "Bu gün 'narahat sükutları doldurmaq üçün söz ehtiyatım' tükənib.",
    "Mənim 'sosial batareyam' yalnız bir nəfərlikdir, o da özüməm.",
    "Bu gün 'öz kölgəmlə daha yaxşı yola gedirəm', nəinki insanlarla.",
    "Mənim 'ictimai maskam' bu gün ütüdə qalıb.",
    "Bu gün 'insanların aurasını oxumaqdan yorulmuşam'.",
    "Mən 'qəribə komplimentlər etməkdən qorxuram', ona görə susuram.",
    "Bu gün 'yanlış adla müraciət etmə fobiyam' kəskinləşib.",
    "Mənim 'əl sıxma texnikam' hələ mükəmməl deyil, riskə gedə bilmərəm.",
    "Bu gün 'insanların arasında görünməz olmağa çalışıram'.",
    "Mənim 'sosial naviqatorum' bu gün 'siqnal tapmır'.",
    "Bu gün 'özümlə daxili dialoqlarım' o qədər maraqlıdır ki, başqalarına vaxt qalmır.",
    "Mən 'kütlə psixologiyasından qorunmaq üçün' tək qalmağı seçirəm.",
    "Bu gün 'yeni insanlarla tanış olmaq üçün enerji kvotam' dolub.",
    "Mənim 'zarafatlarımın anlaşılmama ehtimalı' bu gün çox yüksəkdir.",
    "Bu gün 'hər kəsin məni mühakimə etdiyi paranoyası' ilə mübarizə aparıram.",
    "Mən 'sosial kəpənək deyiləm, daha çox sosial tırtılam', hələ qozamdayam.",
    "Bu gün 'insanların şəxsi məkanına hörmət etmək üçün' onlardan uzaq dururam.",
    "Mənim 'telefondan başını qaldırmamaq' super gücüm bu gün aktivdir.",
    "Bu gün 'səssizcə kənarda dayanıb müşahidə etmək' rolunu seçmişəm.",
    "Mənim 'üz ifadələrim' bu gün 'daxili dünyamı düzgün əks etdirmir'.",
    "Bu gün 'yalnız kitab qəhrəmanları ilə ünsiyyət qurmaq' əhvalım var."
  ]
}

}